### ISSUE TITLE
[1.2.4] BTC maker fee change via governance has no effect

### ISSUE THREAD

**Issue by julianknutsen** [bisq-network/bisq#3742] opened 2019-12-03 23:06 UTC
### Description

Changing the BTC maker fee via governance has no effect on offer creation

#### Version

5880ad99c

### Steps to reproduce

1. create localnet cluster
2. change BTC maker fee parameter via DAO->Governance
3. Create offer expecting to see new values in transaction
4. See all values the same

### Expected behaviour

BTC maker fee should influence some field of the offer when creating it

### Actual behaviour
Nothing seems to change

### Screenshots

![btc_maker_fee_not_changed](https://user-images.githubusercontent.com/8082291/70097499-6767cb80-15de-11ea-90dd-3259c3c9da2f.JPG)

#### Device or machine

Ubuntu 19.10

#### Additional info

[alice-bisq.log](https://github.com/bisq-network/bisq/files/3919130/bisq.log)
[bob-bisq.log](https://github.com/bisq-network/bisq/files/3919131/bisq.log)

Maker fee seems to be correct in the OfferPayload. Am I just misinterpreting when it is used?

```
     date=Tue Dec 03 15:23:54 PST 2019,
     ownerNodeAddress=localhost:5555,
     pubKeyRing=PubKeyRing{signaturePubKeyHex=308201b73082012c06072a8648ce3804013082011f02818100fd7f53811d75122952df4a9c2eece4e7f611b7523cef4400c31e3f80b6512669455d402251fb593d8d58fabfc5f5ba30f6cb9b556cd7813b801d346ff26660b76b9950a5a49f9fe8047b1022c24fbba9d7feb7c61bf83b57e7c6a8a6150f04fb83f6d3c51ec3023554135a169132f675f3ae2b61d72aeff22203199dd14801c70215009760508f15230bccb292b982a2eb840bf0581cf502818100f7e1a085d69b3ddecbbcab5c36b857b97994afbbfa3aea82f9574c0b3d0782675159578ebad4594fe67107108180b449167123e84c281613b7cf09328cc8a6e13c167a8b547c8d28e0a3ae1e2bb3a675916ea37f0bfa213562f1fb627a01243bcca4f1bea8519089a883dfe15ae59f06928b665e807b552564014c3bfecf492a03818400028180148f63287bd232bf2d123f2eace4dd05610f6d3456697cba2ad4e2004857b2755eee4d99a441ead74641dc5dcefcf815568852651746d0a3e7336bb95c2275eb4f24f4442fc48a8fe963250a4181c4004207a44ca2adbd0632ff542e02216e3ac7f7734ca742d4a4df99c1baeaf757373c5e01ee15c64e4d7d05703ebe9eadc1, encryptionPubKeyHex=30820122300d06092a864886f70d01010105000382010f003082010a02820101008297a3bfb6e9f8d60c0cec0c2ed293f0ffbdae58c54cb2b6d792ab495125e1235b2b4600155dc28abd1677d4caea17b1bfc9290312bc0dfdb17795ca17e93f064f996847daa5587d91440661f3046d29451a0f786a013b4d7a65aeb2002c1ee39e95e23397bb9fc65498d05da7a9e48f6a5a0935a6219c122717d3d6d0dda569bc1b1426d59937c116d97df4e30dbf26047fcd5496716c5326ec077c8257ee7e2850c04fa312b7fce6b208de3deeffc5e51df31c7c158475654b8c163a4a57d0ce8287d78e60857244cfe2dcf51aca96322648261af4e960a2fedc912e9e77798011bbacb23c0c19fa01523853afdf0c3824085f3e412b582d2542a18b04739f0203010001},
     direction=BUY,
     price=0,
     marketPriceMargin=0.0,
     useMarketBasedPrice=true,
     amount=1000000,
     minAmount=1000000,
     baseCurrencyCode='ETH',
     counterCurrencyCode='BTC',
     paymentMethodId='BLOCK_CHAINS',
     makerPaymentAccountId='d55040c4-aff4-4ed4-a900-73df578f9d2a',
     offerFeePaymentTxId='41ee6351c981aa1bf81d33551a2abeb2922d71906fabe21b8ba55549f5a2438c',
     countryCode='null',
     acceptedCountryCodes=null,
     bankId='null',
     acceptedBankIds=null,
     versionNr='1.2.4',
     blockHeightAtOfferCreation=202,
     txFee=2600,
     makerFee=5500,
     isCurrencyForMakerFeeBtc=true,
     buyerSecurityDeposit=100000,
     sellerSecurityDeposit=500000,
     maxTradeLimit=200000000,
     maxTradePeriod=86400000,
     useAutoClose=false,
     useReOpenAfterAutoClose=false,
     lowerClosePrice=0,
     upperClosePrice=0,
     isPrivateOffer=false,
     hashOfChallenge='null',
     extraDataMap={capabilities=0, 1, 2, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14},
     protocolVersion=2
} 
```

**Comment by chimp1984** [comment] 2019-12-04 03:35
It becomes active at the upcoming cycle. Have you created blocks to jumpt to next cycle?

**Comment by julianknutsen** [comment] 2019-12-04 06:17
@chimp1984 Yes... that is why I included the screenshot showing the updated current value as well as the OfferPayload output that also shows the makerFee value that are both updated. So I'm either missing when that value is used, or it isn't actually used anywhere.

**Comment by ripcurlx** [comment] 2019-12-04 16:17
@julianknutsen I just tried to reproduce it, but it worked for me as expected.
First before any change in a 1 BTC trade
![Bildschirmfoto 2019-12-04 um 17 09 37](https://user-images.githubusercontent.com/170962/70159588-753e4f00-16b9-11ea-99fd-8ab335d99a95.png)
![Bildschirmfoto 2019-12-04 um 17 09 57](https://user-images.githubusercontent.com/170962/70159590-753e4f00-16b9-11ea-87a0-276aa0f1a3a2.png)
And after a parameter change by voting in the next cycle (proposal phase)
![Bildschirmfoto 2019-12-04 um 17 12 16](https://user-images.githubusercontent.com/170962/70159657-8d15d300-16b9-11ea-95cc-d98d405382f7.png)
![Bildschirmfoto 2019-12-04 um 17 12 25](https://user-images.githubusercontent.com/170962/70159659-8d15d300-16b9-11ea-9eb1-a71665fb0541.png)
![Bildschirmfoto 2019-12-04 um 17 13 07](https://user-images.githubusercontent.com/170962/70159661-8dae6980-16b9-11ea-953f-b8d2dd97749c.png)

What you are seeing is the minimum maker fee of 0.0005 BTC which results in your case in 0.50%  trading fee.

**Comment by ripcurlx** [comment] 2019-12-04 16:19
Closing this issue, because the behavior is as expected. Maybe we should add an additional information that in this case the minimum trading fee is applied. Already caused confusion in the past when people where assuming that the percentage always stays the same no matter if they trade small or large amounts.

**Closed as completed by ripcurlx** 2019-12-04 16:19 UTC
Labels: was:incorrect

**Comment by julianknutsen** [comment] 2019-12-04 16:41
Confirmed NOTABUG.

It was 100% the minimum trading fee taking precedence that caused my confusion. I was always doing small trades so it never changed.

I appreciate you double-checking this to help me understand.
