### ISSUE TITLE
Publishing of an buy offer of BTC for GBP via bank transfer fails resulting in loosing BTC for deposit and mining fee

### ISSUE THREAD

**Issue by sundy12** [bisq-network/bisq#1146] opened 2018-01-03 03:34 UTC
It happened to me twice consecutively. And no offer is being created. I am fed up.
I lost about 40 £ now.  0.003579 BTC.  Will I get it back?
https://bitaps.com/112d1aa1e7ac3e9011829b115833afa9318471cb47f41c5ea93f1aebe73ec076
https://bitaps.com/aa40f26373cfaae4696084016a5cd24aba55dd8d6
4552006181e2d9db19747ad

See

**Comment by sundy12** [comment] 2018-01-03 03:44
Sorry the other transaction is 
https://bitaps.com/aa40f26373cfaae4696084016a5cd24aba55dd8d64552006181e2d9db19747ad

**Comment by ManfredKarrer** [comment] 2018-01-03 22:52
Thanks for reporting. Your log file helped me to spot the potential reason for the issue.
 
Please get in touch with @cbeams regarding the lost trade fee.

**Comment by sundy12** [comment] 2018-01-04 05:18
I keep having the same problem again and again, another loss:
https://bitaps.com/e2abd16fb6a28ba67c96660769e8a34327c47d74d54866efc96c391aad8530b9
0.001787
https://bitaps.com/6aaac716952b09f3906a7556dfa011ab086932d047827f8576dc07d6b326fb1d
0.001878

This is a critical issue.
Can you tell me at least some workaround. I am scared to use your software now , even though I would like to.

**Comment by ManfredKarrer** [comment] 2018-01-04 17:38
The potential reason might be that a dependent not confirmed tx was using version 2 (timelock tx) and BitcoinJ does not recognize such a tx (they added it recently but not merged to our fork yet). I still need more time to test and investigate if that caused the issue. 
If that is the case the issue will be gone if all your UTXOs are confirmed and you don't have other UTXOs from version 2 transactions. But cannot guarantee yet this is the reason for the failed tx. I hope I get a solution in the next days/week and a new release.

**Comment by sundy12** [comment] 2018-01-04 22:39
1)
https://bitaps.com/29b0d5bee26aff49fdf6d0b88ff8db85ff660fe67d174f304a72cbcedbf7c16d
again loss 0.001752
Total loss above 0.01 BTC now (100 GBP)
2)
Can you poke Chris chris@beams.io to reach me  to compensate me (pay me into my wallet) for those regular losses due to bug and crush? 
He has not yet replied to my email. 

3) What is UTXO? What is BitcoinJ?

4) What is your theory why it works sometimes and sometimes does not? I would expect the publishing either always work or  it never works.

5) Manfred. I removed link to the log file due to the disclosed private information (IP).  I assume you already have it locally for your investigation.

**Comment by cbeams** [comment] 2018-01-04 22:44
@sundy12, I've received your email and have this in my queue. I will be processing your reimbursement along with those of others next week. Please stand by, it's been a busy few weeks here and we're still catching up.

**Comment by tr37ion** [comment] 2018-01-06 15:45
@cbeams How about using Github's new Kanban board **Projects** next to the **Issues** tab. You could move all refund related issues in a **Refunds**  or **In Progress** column and people easily see in which stage their refund issue is. Makes if possibly easier for you, too.

**Comment by cbeams** [comment] 2018-01-07 10:30
Because not everyone involved has a GitHub account, and not everything shared should be made public via GitHub. I have a simple email folder-based workflow set up to track everything. Thanks for the thought, though.

**Comment by ripcurlx** [comment] 2018-12-20 10:32
As lots of optimizations took place in the message and transaction handling I'm closing this issue for now. Feel free to reopen if these kind of problems occur again.

**Closed as completed by ripcurlx** 2018-12-20 10:32 UTC
