### ISSUE TITLE
Unable to move missing deposit tx trade to failed trades

### ISSUE THREAD

**Issue by MwithM** [bisq-network/bisq#4905] opened 2020-12-07 08:15 UTC
### Description

After a couple days without the deposit tx (which was displayed at Bisq UI) being broadcasted, mediator tells me to make a SPV resync and send trade to failed.
After SPV resync, this "null deposit tx, send to failed" warning is displayed.
![imagen](https://user-images.githubusercontent.com/50149324/101325228-b38dc180-386b-11eb-8728-5a3d2fe8f263.png)
But it's not possible to send it to failed. I still have locked funds.

#### Version

1.5

### Expected behaviour

Red symbol at the top right of the trade should appear, to move trade to failed.

### Actual behaviour

No red symbol. Funds locked.

### Screenshots

![imagen](https://user-images.githubusercontent.com/50149324/101325699-7aa21c80-386c-11eb-94ce-21e7bea991c4.png)

#### Device or machine

Linux Mint.

**Comment by pazza83** [comment] 2020-12-08 00:18
I have the same problem.

I was the Maker, Taker deposit transaction did not broadcast.

Taker opened mediation.

Mediator issued manual payout.

Currently the trade is in my open trades.

Selecting the pending trade and pressing: 'Ctrl + y' or 'alt + y' or 'cmd + y' does not work.

**Comment by MwithM** [comment] 2020-12-08 17:16
> Selecting the pending trade and pressing: 'Ctrl + y' or 'alt + y' or 'cmd + y' does not work.

That's to unfail a trade. Moves a trade from failed trades to open trades. It's used when the deposit tx is confirmed but Bisq doesn't recognize it.

Also, in my case there have not been manual payout, and funds are still displayed as locked in Bisq.

**Comment by pazza83** [comment] 2020-12-08 19:04
> That's to unfail a trade. Moves a trade from failed trades to open trades. It's used when the deposit tx is confirmed but Bisq doesn't recognize it.

Thanks for letting me know. Is this description incorrect then? Maybe I am reading it wrong?

![y](https://user-images.githubusercontent.com/66367547/101528953-ceedef00-3987-11eb-8ff2-67b832d9149c.png)

> Also, in my case there have not been manual payout, and funds are still displayed as locked in Bisq.

Yes this is different. My fund are not locked. This is a shot of my trade. Clock does not move. Trade is already completed.

![stuck](https://user-images.githubusercontent.com/66367547/101529113-08bef580-3988-11eb-8feb-9574b0be7eb5.png)

**Comment by MwithM** [comment] 2020-12-08 19:38
Indeed the shortcut says what you meant (send to failed), which is not how it was used and described [here](https://bisq.wiki/Failed_trades) (unfail).

**Comment by oscarguindzberg** [comment] 2020-12-08 20:48
@MwithM @pazza83 could you send me the bisq maker and taker logs at the time the trade was taken?

**Comment by MwithM** [comment] 2020-12-08 21:31
My trades are mediated and closed, I only can provide mine (maker).

**Comment by MwithM** [comment] 2020-12-08 21:31
I'm only providing mine, as maker. Trade is already closed and I can't contact with peer.

**Comment by chimp1984** [comment] 2020-12-08 22:14
Moving a trade without deposit tx is fixed with https://github.com/bisq-network/bisq/pull/4921

**Comment by oscarguindzberg** [comment] 2020-12-09 04:04
I checked @MwithM logs. 
deposit tx is invalid because maker fee tx is invalid. That's why none of those appear in block explorers.
maker fee tx is invalid because it spends an already spent output.
It spends an already spent output because the tx that originally spent that output is not present in the bitcoinj wallet, so bitcoinj thinks that utxo is available.
I see in the logs when the wallet is getting up to date with the blockchain / spv resynced / restored from seed the tx that originally spent that output is not being received by the wallet when the block it is included in is processed by bitcoinj.

**Comment by chimp1984** [comment] 2020-12-09 04:07
> I see in the logs the when the wallet is getting up to date with the blockchain / spv resynced / restored from seed the tx that originally spent that output is not being received by the wallet when the block it is included in is processed by bitcoinj.

What do you think is the reason for that? Bloomfilter issue?

**Comment by oscarguindzberg** [comment] 2020-12-09 04:11
> > I see in the logs the when the wallet is getting up to date with the blockchain / spv resynced / restored from seed the tx that originally spent that output is not being received by the wallet when the block it is included in is processed by bitcoinj.
> 
> What do you think is the reason for that? Bloomfilter issue?

maybe. not sure yet.

**Comment by oscarguindzberg** [comment] 2020-12-09 05:55
more info on @MwithM case: the output trying to be spent is a "reserved for trade" output and the tx that originally spent that output is a deposit tx. I think spv resync / restore from seed restored the "fee tx" but not the "deposit tx" and marked the "fee tx" output as available.

**Comment by oscarguindzberg** [comment] 2020-12-09 06:02
Maybe https://github.com/bisq-network/bisq/issues/4870, https://github.com/bisq-network/bisq/issues/4911 and this issue have the same root cause: a deposit tx not being informed by bitcoin core to bitcoinj when sending the filtered block.

**Closed as completed** 2020-12-09 09:12 UTC
