### ISSUE TITLE
Error b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread

### ISSUE THREAD

**Issue by phbassett** [bisq-network/bisq#6486] opened 2022-12-25 23:46 UTC
### Description

ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
ERROR b.c.s.CommonSetup: throwableMessage= Task TrustedListenableFutureTask@2028f0ca[status=PENDING, info=[task=[running=[NOT STARTED YET], bisq.network.p2p.network.NetworkNode$$Lambda$1419/0x000000010081cc28@5cf42f04]]] rejected from java.util.concurrent.ThreadPoolExecutor@5206d03[Running, pool size = 36, active threads = 36, queued tasks = 30, completed tasks = 281824] 
ERROR b.c.s.CommonSetup: throwableClass= class java.util.concurrent.RejectedExecutionException 
ERROR b.c.s.CommonSetup: Stack trace:

#### Version
Ver. 1.9.8

### Steps to reproduce

Error message appeared on screen requesting log files to be sumbitted.

#### Additional info

[12252022bisqerror.txt](https://github.com/bisq-network/bisq/files/10300788/12252022bisqerror.txt)

**Comment by swarna1101** [comment] 2022-12-26 11:26
The error message "ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread" indicates that an uncaught exception was thrown from the JavaFX application thread, which is responsible for running the user interface of a JavaFX application.

The error message also mentions that the task was rejected from the thread pool executor, which suggests that the thread pool was unable to execute the task because it was already at its maximum capacity and had no available threads to run the task.

Without more information about the specific context in which this error occurred, it is difficult to provide a specific diagnosis or solution for this issue. It is possible that the error was caused by a resource contention issue, such as if the application was trying to access a resource that was already being used by another thread. It is also possible that the error was caused by a bug in the application.

To troubleshoot this issue, you may want to try the following steps:

1. Review the log file (12252022bisqerror.txt) that was requested to be submitted. This log file may contain additional information about the error, such as a stack trace that can help identify the root cause of the issue.
2. Check the system resources (e.g., CPU, memory, disk space) on the machine where the application is running. If the system is running low on resources, it could be causing the thread pool executor to reject tasks.
3. Check for updates to the application. If there is a newer version available, it may contain fixes for known issues that could be causing this error.
4. If the issue persists, you may want to consider seeking help from the developers of the application or from a community of users. They may be able to provide more specific guidance on troubleshooting and resolving the issue.

**Closed as not planned** 2023-08-18 00:13 UTC
Labels: was:dropped
