### ISSUE TITLE
[0.4.8.1] (generateKeyPair) Exception when registering the cryptographic service provider

### ISSUE THREAD

**Issue by martysto** [bisq-network/bisq#523] opened 2016-07-08 17:13 UTC
Starting with the recent release 0.4.8.1 the following exception is thrown after startup (java -jar Bitsquare-0.4.8.1.jar ):

```
java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
    at javax.crypto.JceSecurity.getInstance(JceSecurity.java:101)
    at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:265)
    at io.bitsquare.common.crypto.Encryption.generateSecretKey(Encryption.java:252)
    at io.bitsquare.common.crypto.Encryption.encryptHybridWithSignature(Encryption.java:211)
    at io.bitsquare.gui.main.MainViewModel$4.run(MainViewModel.java:530)
Caused by: java.util.jar.JarException: file:/opt/Bitsquare/app/Bitsquare-0.4.8.1.jar has unsigned entries - i18n/displayStrings.properties
    at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:464)
    at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:322)
    at javax.crypto.JarVerifier.verify(JarVerifier.java:250)
    at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:160)
    at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:186)
    at javax.crypto.JceSecurity.getInstance(JceSecurity.java:98)
    ... 4 more
Jul-08 17:52:02.118 [Thread-24] ERROR i.b.c.c.Encryption: JCE cannot authenticate the provider BC 
Jul-08 17:52:02.128 [Thread-24] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread Thread-24 
Jul-08 17:52:02.128 [Thread-24] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Couldn't generate key 
java.lang.RuntimeException: Couldn't generate key
    at io.bitsquare.common.crypto.Encryption.generateSecretKey(Encryption.java:258)
    at io.bitsquare.common.crypto.Encryption.encryptHybridWithSignature(Encryption.java:211)
    at io.bitsquare.gui.main.MainViewModel$4.run(MainViewModel.java:530)
```

**Comment by martysto** [comment] 2016-07-08 17:23
Also, it starts just fine and I get only a message to report the error. Maybe it's better to abort the startup if this fails?

**Comment by ManfredKarrer** [comment] 2016-07-08 17:31
Do you run the jar file directly? If so you need to follow all the steps at the https://github.com/bitsquare/bitsquare/blob/master/doc/build.md#prerequisites.
When you run the binary, the packaged JRE has those extra parts included.
If you got that error from running the binary, please let me knwo which OS.

Yes to shut down directly might be a good idea. You cannot trade when the BC is nto available.

**Comment by ManfredKarrer** [comment] 2016-07-08 17:32
I close it as it seems its caused by running the jar without setting up the jdk. If not please re-open it.

**Closed as completed by ManfredKarrer** 2016-07-08 17:32 UTC

**Comment by martysto** [comment] 2016-07-08 19:10
Yes, you are right. The confusion was that the vanilla installation requires open JDK to work which is part of openjfx ... I had only Oracles JDK, resulting in:
./Bitsquare: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

Thanks for the swift feedback!
