### ISSUE TITLE
Timeout when placing an offer

### ISSUE THREAD

**Issue by csacher** [bisq-network/bisq#1150] opened 2018-01-04 12:08 UTC
![bildschirmfoto 2018-01-04 um 13 04 15](https://user-images.githubusercontent.com/34270328/34562763-0b6ac53a-f150-11e7-8cc7-093ca1d88217.JPG)

Again produced timeout error after placing an offer to sell BTC. 
Funds are locked in escrow wallet. Please also refund the fees and what happens with mining fees?

Cheers

**Comment by csacher** [comment] 2018-01-04 12:23
![bildschirmfoto 2018-01-04 um 13 22 40](https://user-images.githubusercontent.com/34270328/34563288-614574c6-f152-11e7-80db-b5c8e23d1388.JPG)

tried again, one more timeout. fees still not back in my account.

**Comment by cbeams** [comment] 2018-01-04 13:05
@csacher, @ManfredKarrer believes he's found the root cause for these timeouts, and if he's correct about it, then if it happens once, it'll happen every time you try to pay fees for a trade from the same chain of transactions. Can't explain fully now, but I would recommend holding off on trading for the moment if you're experiencing this problem.

Any funds lost above will be reimbursed. Please send me an email about it and I'll get you in the queue, thanks.

**Comment by csacher** [comment] 2018-01-04 16:10
@cbeams Mail is on the way. 3rd time I tried it worked.

**Comment by ManfredKarrer** [comment] 2018-01-04 16:57
@csacher Can you send me the log file?

**Comment by khowell30** [comment] 2018-01-06 02:21
I have the same issue when placing an offer to buy BTC.

<img width="1175" alt="screen shot 2018-01-05 at 9 17 59 pm" src="https://user-images.githubusercontent.com/35157196/34635488-4163bc64-f25e-11e7-92f1-c7e1d02963c7.png">
g

What's the solution, and when will the funds be returned?

**Comment by The-Beginning** [comment] 2018-01-06 15:48
@csacher @ManfredKarrer I had the same issue happen to me today and was wondering how do I get reimbursed? I placed the order from my built in account, it time'd out, and the order didn't go through but my funds were withdrawn. I've used the platform before, yrs ago, and I never went through something like this. Please help. 
Let me know what I have to do.
Thank You.

**Comment by ManfredKarrer** [comment] 2018-01-06 16:27
@The-Beginning 
Please contact @cbeams regarding the lost fee.

Can you please send me the log file (account/backup/ button to open log) and the tx list exported as csv (funds/tx) as well as the trade id and tx id of the failed fee tx? My email is manfred at bitsquare dot io.

**Comment by khowell30** [comment] 2018-01-06 19:34
@ManfredKarrer 
I see your response to @The-Beginning , who has the exact same issue I posted just before him
I've sent email to @cbeams 

Do you need my log file as well?

**Comment by cbeams** [comment] 2018-01-14 14:13
@The-Beginning, I am not sure whether you ever contacted my about this lost fee. Please send me an email at chris@beams.io mentioning your GitHub username and linking to this issue, and please also include the transaction ID of the trade that timed out. I'll get back to you from there. Thanks.

**Comment by The-Beginning** [comment] 2018-01-14 17:22
Good Afternoon, thanks you for inquiring about this matter. It has already 
been resolved. Thank you for double checking though.
Thank you again.

**Comment by cbeams** [comment] 2018-01-14 21:26
Got it, @The-Beginning. Thank you.

**Comment by cbeams** [comment] 2018-01-18 05:54
Closing as superseded by bisq-network/support#1, which itself is now complete, with reimbursements having been paid out by batch transaction. See the closing comment there for details.

**Closed as completed by cbeams** 2018-01-18 05:54 UTC
Labels: was:superseded
