### ISSUE TITLE
Use Webcam failed

### ISSUE THREAD

**Issue by bengregori** [bisq-network/bisq#4176] opened 2020-04-16 23:32 UTC
### Description

Under Account, I selected the "Scan QR Code" button under the Use Webcam section, and received an error.  Attached is the log file.

#### Version

v1.3.1

### Expected behaviour

I presume the expected behavior was to open my webcam application to snap a picture of a QR code.

### Actual behaviour

An error occurred and suggested I submit a GitHub issue and prompted me to download the log file.

#### Device or machine

System Model	HP Spectre x360 Convertible 13-w0XX
, Windows 10 Home v.10.0.18363 Build 18363

#### Additional info

[bisq.log](https://github.com/bisq-network/bisq/files/4490148/bisq.log)

**Comment by ripcurlx** [comment] 2020-04-20 14:30
> An error occurred and suggested I submit a GitHub issue and prompted me to download the log file.

It should use your laptops webcam capability to snap a picture. 

```
Apr-16 19:26:06.577 [JavaFX Application Thread] INFO  b.d.m.a.c.n.MobileNotificationsView: Start WebCamLauncher 
Apr-16 19:26:06.593 [Thread-25] INFO  c.g.s.w.Webcam: WebcamDefaultDriver capture driver will be used 
Apr-16 19:26:07.599 [Thread-25] ERROR b.d.m.a.c.n.WebCamLauncher: java.util.concurrent.TimeoutException: Webcams discovery timeout (1000 ms) has been exceeded 
Apr-16 19:26:07.599 [webcam-discovery-service] ERROR c.g.s.w.d.b.WebcamDefaultDriver: Processor has been interrupted 
Apr-16 19:26:07.600 [JavaFX Application Thread] ERROR b.d.m.a.c.n.MobileNotificationsView: java.util.concurrent.TimeoutException: Webcams discovery timeout (1000 ms) has been exceeded 
```

I guess your webcam does work if you launch it normally? The app had issues connecting to your webcam.

**Comment by ricardosaurio** [comment] 2020-06-13 22:31
Sorry for chiming in, but i had the same issue, i solved it by openinga webcam testing page easily found in google, and it worked there. Afterward, it worked on Bisq. I guess the goal is not to do these steps, but while its being debugged, you can try that, see how it goes.

**Comment by cd2357** [comment] 2020-10-13 14:19
If it works after the webcam is fist tested on some webpage, then the issue is probably related to webcam initialization when accessing it from Bisq.

**Comment by drrossum** [comment] 2020-11-19 10:18
The issue for me was caused by /tmp being mounted with the noexec option. The workaround was to temporarily remount exec:
mount -o remount,exec /tmp
mount -o remount,noexec /tmp

**Comment by ripcurlx** [comment] 2020-12-14 10:49
Closing as complete

**Closed as completed by ripcurlx** 2020-12-14 10:49 UTC
Labels: a:bug, good first issue
