### ISSUE TITLE
Transaction returned to "start payment2 status after PC restarted

### ISSUE THREAD

**Issue by Stam57** [bisq-network/bisq#4805] opened 2020-11-14 10:02 UTC
SUPPORT REQUESTS: This is for reporting bugs in the Bisq app.
   If you have a support request, please join #support on Bisq's
   Keybase team at https://keybase.io/team/Bisq

### Description

 Last night I completed the transaction by paying the seller. The seller verified the payment and I received in my phone a 'transaction complete' message through the bisq app. I never visited the bisq app in my PC after that until this morning when I realised that the PC had done an automatic restart because of some new windows updates. When I opened bisq in the PC I received a warning message about the time left to complete the transaction. I pressed the 'payment started' button and then I received the warning about the bug.

#### Version
1.4.2

### Steps to reproduce

as in descripion above 

### Expected behaviour

the transaction should have been ended and completed

### Actual behaviour

 the transaction returned to a previous step (step 2: start payment)

#### Device or machine

windows 10, intel CPU

#### Additional info

 Additional information useful for debugging (e.g. logs)
[bisq1.log](https://github.com/bisq-network/bisq/files/5540450/bisq1.log)

**Comment by cd2357** [comment] 2021-03-29 15:16
Duplicate of #4806

**Closed as completed by cd2357** 2021-03-29 15:16 UTC
Labels: a:bug, in:trade-process
