### ISSUE TITLE
Unconfirmed transactions cause confusion

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#2076] opened 2018-12-06 14:05 UTC
In my wallet balance it shows 0 BSQ as available balance and the rest is in the unverified field. But in the list on the bottom it says that it has already 11 blockchain confirmations. 
<img width="1312" alt="bildschirmfoto 2018-12-06 um 15 02 56" src="https://user-images.githubusercontent.com/170962/49588874-2ce63700-f968-11e8-97f0-96f370147f41.png">

**Comment by ripcurlx** [comment] 2018-12-06 14:09
As soon as all transactions where confirmed the available balance was updated correctly. Seems that they blocked somehow the other transactions as well to be accounted as available?
<img width="1312" alt="bildschirmfoto 2018-12-06 um 15 07 59" src="https://user-images.githubusercontent.com/170962/49589143-e6dda300-f968-11e8-83c5-af211a9a7387.png">

**Comment by ManfredKarrer** [comment] 2018-12-06 15:40
Only confirmed BSQ utxos are counted for availabel balance. The utxo from past txs have been used for the new tx so they are not valid anymore. That is a bit confusing I know but BSQ is only suporting confirmed txs atm. We might in future add support for displaying pending txs which are likely become BSQ but there is no guarantee as long the block is not validated. In Bitcoin other nodes are only reying txs which are valid BTC tx but they dont know about BSQ rules, so its a different security situation. Probably better text which explains it better that only confirmed txs are considered should be found.

**Comment by ManfredKarrer** [comment] 2018-12-06 15:41
I changed the title to reflect the problem to be fixed.

**Comment by devinbileck** [comment] 2018-12-06 22:31
Additionally, the `Amount in BSQ` column within the table shows `N/A` while the transaction is unconfirmed even though the amount from that transaction is shown in the `Unverified` field above the table. Since it is included in the `Unverified` field, I assume it should be shown in the `Amount in BSQ` column?

**Comment by ManfredKarrer** [comment] 2019-01-29 20:37
@devinbileck The tx item should show the amount you are transferring. As we don't know that it before confirmation it is hard to show here anything. The amoun in `Unverified` field on the top is the sum of all unconfirmed UTXOs, so not really the amount we want to show in the tx item. 
@sqrrm is working on a PR for supporting own unconfirmed UTXOs from change outputs, that might help here as well once that is done. But not sure as its a bit complex.

**Comment by ManfredKarrer** [comment] 2019-03-12 20:30
Close it as it is implemented already

**Closed as completed by ManfredKarrer** 2019-03-12 20:30 UTC
Labels: in:gui, in:dao
