### ISSUE TITLE
Error -1

### ISSUE THREAD

**Issue by dougbebber** [bisq-network/bisq#428] opened 2016-05-04 01:55 UTC
Walked away from computer leaving BitSquare running I get the following error message on return.
Running BitSquare 0.4.6 on Mac OS X El Capitan version 10.11.2

<img width="744" alt="screen shot 2016-05-03 at 8 52 55 pm" src="https://cloud.githubusercontent.com/assets/2474050/15003401/0bb91fac-1171-11e6-9860-9b0f5175e1f3.png">

**Comment by ivilata** [comment] 2016-05-04 07:00
Maybe a duplicate of #421?

**Comment by ManfredKarrer** [comment] 2016-05-05 11:53
Fixed with https://github.com/bitsquare/bitsquare/commit/afb8c18d31825453e0070c0dc944867c42e627e7
Will be deployed with next version.

**Closed as completed by ManfredKarrer** 2016-05-05 11:53 UTC
