### ISSUE TITLE
Is there any API in bitsquare ?

### ISSUE THREAD

**Issue by albabosh** [bisq-network/bisq#801] opened 2017-04-14 08:38 UTC
Is there any API in bitsquare ? I want to trade at bitsquare with my own trading client.

**Comment by mrosseel** [comment] 2017-04-14 09:03
Hi, not yet but it's being worked in branch issue544-api

**Comment by Piste** [comment] 2017-07-12 02:15
Linking to 544: https://github.com/bitsquare/bitsquare/issues/544

**Comment by Piste** [comment] 2017-07-12 02:16
@albabosh , May I suggest adding a +1 to #544 and closing this issue?

**Comment by mrosseel** [comment] 2017-07-17 12:48
issue closed, duplicate of #544

**Closed as completed by mrosseel** 2017-07-17 12:48 UTC
