### ISSUE TITLE
Bisq stats module in monitor not showing data 

### ISSUE THREAD

**Issue by embitkay** [bisq-network/bisq#5297] opened 2021-03-13 02:12 UTC
### Description

The ["bisq stats" Grafana widget](https://monitor.bisq.network/d/tnBzsrOWk/bisq-stats) is not showing any data

#### Version

n/a

### Steps to reproduce

n/a

### Expected behaviour

Data should be showing

### Actual behaviour
Data isn't showing

### Screenshots
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/80179404/111015584-6b94a400-835e-11eb-91e8-12b4d41e1774.png">

#### Device or machine

MacOS (Firefox browser)

#### Additional info

n/a

**Comment by wallclockbuilder** [comment] 2021-03-13 02:14
Steps to reproduce

Visit https://monitor.bisq.network/d/tnBzsrOWk/bisq-stats

**Comment by ripcurlx** [comment] 2021-03-15 09:33
Since it was moved from the old monitor maintainer @freimair to @emzy this wasn't fixed yet.  We are aware of it, it just needs someone to look into the monitor part together with Emzy to get it working again. @wallclockbuilder Maybe that is something you want to look into?

**Comment by wallclockbuilder** [comment] 2021-03-15 15:59
Sure. Assign it to me.

**Comment by wallclockbuilder** [comment] 2021-03-15 17:13
Oops. Thought it was my issue. Please assign to issue author @embitkay

**Comment by wallclockbuilder** [comment] 2021-03-15 17:16
@embitkay  is interested in working on this. You're suggesting I pair with @Emzy on this. 
Perhaps you can assign it to us all and then we can pair on it.

**Comment by embitkay** [comment] 2021-03-16 02:43
Thanks all and yes, very interested in working on this. I'm really passionate about interactive visualisations and have been doing it professionally for the past several years. Happy to find a place I can contribute. Still working my way through on-boarding. 

@Emzy do you have any immediate insight into what is broken, or do we still need to discover the reason for the bug?

**Comment by cd2357** [comment] 2021-05-10 21:36
@wallclockbuilder @embitkay Any updates? I was recently looking at the monitor and it didn't look good.

Alternatively, if its not maintained, is it even worth "keeping it alive" anymore? (i.e. linking to it, keeping the subdomain https://monitor.bisq.network etc)?

**Closed as completed** 2021-09-06 20:27 UTC
Labels: in:network, was:dropped, in:monitoring

**Comment by xanoni** [comment] 2021-09-26 21:45
Just wanted to report that it 's still broken ... why not take it down? It doesn't leave a good impression if it basically claims that Bisq is broken all around ;-)

<img width="674" alt="image" src="https://user-images.githubusercontent.com/77220130/134825230-d6381591-9540-4fcf-9dc7-219a1b16317b.png">
