### ISSUE TITLE
Governance -> Browse Open Proposals -> NullPointerException

### ISSUE THREAD

**Issue by niyid** [bisq-network/bisq#3116] opened 2019-08-20 17:12 UTC
I experienced an uncaught exception. Stack trace is below:

```
Aug-20 18:01:35.875 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Aug-20 18:01:35.875 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableMessage= null 
Aug-20 18:01:35.876 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.NullPointerException 
Aug-20 18:01:35.916 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
java.lang.NullPointerException
	at bisq.desktop.main.dao.governance.proposals.ProposalsView.lambda$activate$5(ProposalsView.java:212)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)
 
java.lang.NullPointerException
	at bisq.desktop.main.dao.governance.proposals.ProposalsView.lambda$activate$5(ProposalsView.java:212)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)

```

**Comment by devinbileck** [comment] 2019-08-21 07:55
Seems to be a duplicate of #2883

**Comment by niyid** [comment] 2019-08-21 10:49
It is indeed. Apologies for the duplication.

**Closed as completed** 2019-08-21 17:47 UTC
