### ISSUE TITLE
Error - tradersMultiSigKeyPair must not be null

### ISSUE THREAD

**Issue by jomnes** [bisq-network/bisq#938] opened 2017-09-20 14:08 UTC
Hi, I got the abouve popup when starting Bisq this morning.  The popup said to report the issue.

**Comment by ManfredKarrer** [comment] 2017-09-20 14:10
Can you send me the log file (Account/Backup/ button to open log)? manfred at bitsquare dot io

**Comment by MatildeSL** [comment] 2017-09-25 21:28
I have got the same message when trying to introduce my password at bisq

**Comment by ManfredKarrer** [comment] 2017-09-28 02:13
That is caused by a disputed trade where you received 2 times a payout message (when the arbitrator re-opens and payout again because first attempt failed). there is no follow up problems with that just annoying. you can either life with it and wait for the next release where that is fixed or remove in the db folder the disputelist:
PATH to your data directory: bisq/btc_mainnet/db/DisputeList  
data directory can be opened at the menu account/backup

**Comment by MatildeSL** [comment] 2017-10-01 18:41
Thank you for your response. 

The file DisputeList does not appear inside the folder btc_mainnet.
I am running a Mac Os X 10.9.5, and I already reinstall bisq without sucess. Do you have any other suggestions?

**Comment by ManfredKarrer** [comment] 2017-10-01 22:23
It is in: btc_mainnet/db/DisputeList. Re-install does not help. You can start over new by deleting your data directory, but be sure you have sent out all BTC, have no open offer/trades/disputes and exported payment accounts, trade and tx history. Backup, before deleting.

**Comment by ManfredKarrer** [comment] 2017-12-04 20:30
That should be fixed in v06.0

**Closed as completed by ManfredKarrer** 2017-12-04 20:30 UTC
