### ISSUE TITLE
Error -9

### ISSUE THREAD

**Issue by dougbebber** [bisq-network/bisq#429] opened 2016-05-04 03:49 UTC
On BitSquare 0.4.6 on Mac OS X El Capitan ver 10.11.2

Obtained this error when moving from Support page to Offer book page:

<img width="1003" alt="screen shot 2016-05-03 at 10 46 28 pm" src="https://cloud.githubusercontent.com/assets/2474050/15004813/40defc78-1181-11e6-97f2-104091354193.png">

**Comment by ivilata** [comment] 2016-05-04 07:02
Thanks for reporting. This may be related to or a duplicate of #421.

**Comment by ManfredKarrer** [comment] 2016-05-05 11:53
Fixed with https://github.com/bitsquare/bitsquare/commit/afb8c18d31825453e0070c0dc944867c42e627e7
Will be deployed with next version.

**Closed as completed by ManfredKarrer** 2016-05-05 11:53 UTC
