### ISSUE TITLE
Getting java.lang.NumberFormatException and blank/unresponsive Bisq window

### ISSUE THREAD

**Issue by m52go** [bisq-network/bisq#5366] opened 2021-03-28 01:22 UTC
### Description

Since upgrading my Bisq instance to 1.5.9 about 10 days ago, I've gotten this error about 4-5 times:

`Mar-26 20:03:25.028 [JavaFX Application Thread] ERROR b.c.u.MathUtils: java.lang.NumberFormatException: Character I is neither a decimal digit number, decimal point, nor "e" notation exponential mark.`

When this happens, Bisq becomes unresponsive. Usually the Bisq window becomes a blank white rectangle, but sometimes the Bisq GUI remains visible (but not operational).

Also when this happens, I have to kill Bisq and then open it again -- closing Bisq properly doesn't work. So far there haven't been any errors opening properly afterward.

### Version

1.5.9

### Steps to reproduce

I got this error a couple of times last year, but then it went away with an update so I didn't report it.

But I also didn't report it because there's not very much help I can give on reproducing it......

The error seems to occur randomly, and when it occurs, all logs are overwritten so quickly that any clues of the bug's cause are quickly overwritten:

![bisq-error](https://user-images.githubusercontent.com/735155/112739079-bd454d00-8f60-11eb-8793-f1159f2a3153.gif)

Every time this error has happened so far, I wasn't actively using Bisq. Sometimes I was actively using the machine it was running on (but not using Bisq), and sometimes I wasn't using the machine at all (screen locked but machine still on).

Usually I'm tipped off that the error has occurred when I hear the computer fans going crazy.

### Expected behaviour

N/A

### Actual behaviour

N/A

### Screenshots

See above GIF for an idea of what logs look like streaming in real-time.

As noted above, the Bisq window usually turns into a blank white rectangle.

### Device or machine

Ubuntu 18.04

### Additional info

Can provide logs upon request, but these logs will only show logs _after_ this error occurs (i.e., startup after killing the program).

**Comment by wallclockbuilder** [comment] 2021-03-28 02:42
Update to v1.6.0 its coming out on Monday(in 48 hrs). `https://github.com/bisq-network/bisq/tree/release/v1.6.0`

**Comment by cd2357** [comment] 2021-03-28 05:40
@m52go can you look back in the logs at the first time it occurs, and copy paste the stack trace if available?

That would help us better pin-point what is causing it, thanks.

**Comment by m52go** [comment] 2021-03-28 18:36
> can you look back in the logs at the first time it occurs

The errors are thrown so quickly that it's extremely difficult to obtain this. The error is thrown >70 times per _millisecond_, so all the rolling log files are overwritten quickly. A single log file of 11.6 MB has only 2 seconds worth of data in >57,000 lines...so Bisq would need to be stopped within seconds of the bug occurring to get useful logs. So far I haven't been able to do this.

With that said, I didn't realize #5362 might be relevant to this issue. I noticed your comment about disabling hardware graphics acceleration, so I'll experiment with that. I did recently start to toggle my discrete graphics card on/off so maybe that's contributing to this issue. I'll report back soon with results.

**Comment by m52go** [comment] 2021-04-03 03:30
I've been running with the `-Dprism.order=sw` option now for a few days and haven't encountered the error yet, although the GUI is so slow without hardware graphics acceleration that Bisq froze once because of that.

Anyway @cd2357 I see you have a PR open already (!)...would be awesome if it fixes this issue so I can turn hardware acceleration back on. 

Feel free to close this issue, or I guess the PR should close this issue once it's merged.

**Comment by cd2357** [comment] 2021-04-03 07:44
@m52go you can remove the option and use HW acceleration again, seems the issue is caused by something else entirely (investigation ongoing).

**Comment by cd2357** [comment] 2021-04-03 09:28
Smth else you can try @m52go , if your graphics card uses special proprietary drivers, is to try to reinstall or upgrade them, or try switching to open source alternatives for these drivers (if available).

Based on a chat with @wallclockbuilder I have a hunch it might be related to the graphics drivers.

His suggestion https://github.com/bisq-network/bisq/issues/5362#issuecomment-808893949 for someone who had the same issue on Windows, was to reinstall the C++ redistributable packages, which were apparently used by the OS to interface with the graphics card drivers.

That fixed it there, so I'm thinking this could be graphics-driver-related here as well.

Corroborating evidence is that in your case (on Linux), disabling HW acceleration made the issue go away.

So if possible, please try to reinstall/upgrade the graphics drivers, or try using an open-source version of them.

**Comment by wallclockbuilder** [comment] 2021-04-06 02:13
Run it. Get the error. Close it. Share last page of logs.

**Comment by cd2357** [comment] 2021-05-09 11:08
@m52go still an issue with v1.6.4? It comes with the latest JavaFX which should fix a lot of previous UI issues.

**Closed as completed** 2021-09-06 20:27 UTC
Labels: was:dropped
