### ISSUE TITLE
Can't withdraw fund

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#395] opened 2016-04-24 12:02 UTC
Hi, I tried to withdraw funds to my external wallet and this message appear: (you don't have enough fund in your wallet)
Bitsquare version: v0.4.3 Beta preview

![captura de tela de 2016-04-24 08-57-19](https://cloud.githubusercontent.com/assets/1178856/14767437/31f5c1a2-09fb-11e6-8a4d-dfcef75c23de.png)

![captura de tela de 2016-04-24 08-57-30](https://cloud.githubusercontent.com/assets/1178856/14767438/389a0824-09fb-11e6-85b0-b31f1bf6eadc.png)

**Comment by ManfredKarrer** [comment] 2016-04-24 12:54
Ah I think there is a bug in the fee calculation if there have been many transactions. You can simply try to withdraw a smaller amount, then it should work. Ned to investigate whats the cause of that problem...

**Comment by bitcoinuser** [comment] 2016-04-24 12:57
Ok, I prefer to wait for a fix. Thanks.

**Comment by bitcoinuser** [comment] 2016-04-27 01:12
Hi, testing on 0.4.4 version and now the button withdraw selected is disabled.
Obs: If I remove tha last 8 from the value, the button appear as enabled.

![captura de tela de 2016-04-26 22-07-49](https://cloud.githubusercontent.com/assets/1178856/14838837/c9a01c3a-0bfb-11e6-94ef-4b8d3978737e.png)

**Comment by ManfredKarrer** [comment] 2016-04-27 13:05
Hm... damn seems to be still an issue with the fee caclulation. Would u mind to send me your data dir (wallet unlocked), then i can debug it, otherwise its hard to reproduce. i promise i dont steal the btc :-).

**Comment by bitcoinuser** [comment] 2016-04-27 13:08
Sure. Tell me your email and the files you need. I'm using Ubuntu OS.

**Comment by ManfredKarrer** [comment] 2016-04-27 13:17
manfred at bitsquare io

**Comment by bitcoinuser** [comment] 2016-04-27 14:45
Thanks. Later at home, I'll send you the files.

**Comment by bitcoinuser** [comment] 2016-04-28 01:09
Hi,

Sent the files.

Thanks

**Comment by ManfredKarrer** [comment] 2016-04-28 14:53
the reason for the bug is just that the amount in the field gets rounded to 4 decimal places but the real value in the balance can be larger (eg. 0.11113456 instead of 0.1111), so the UI does not handle that correctly.
if you need to withdraw now you can do either manually edit the amount field to a little bit smaller amount or if you don't have offers or trades open use the emergency tool for withdraw all the availabel funds on the wallet. you can open that with cmd+e (or ctrl+e).

a new version with a bugfix will get out soon.

**Comment by bitcoinuser** [comment] 2016-04-28 16:10
Hi,

I will wait the new version. Thanks.

**Comment by ManfredKarrer** [comment] 2016-04-28 16:17
The next days it will be released. I want to get the windows code signing in as well... still waiting for the damn cert....

**Comment by ManfredKarrer** [comment] 2016-04-28 23:10
A new version has been deployed:
https://github.com/bitsquare/bitsquare/releases/tag/v0.4.5

**Closed as completed by ManfredKarrer** 2016-04-28 23:10 UTC
