### ISSUE TITLE
Cannot use custom bitcoin node with onion v3 address

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#4020] opened 2020-03-01 15:17 UTC
Trying to fill an address like ```3gu3q5glljdg6r3fnciuahrfhpa5t26rvyuprevryglph7hhpqc2uiyd.onion:8333```
in ```Use custom Bitcoin Core nodes``` and it does not accept it. Smaller onion addresses are accepted

**Comment by wiz** [comment] 2020-03-01 15:19
duplicate of #2873

**Comment by ripcurlx** [comment] 2020-03-11 08:21
Closing because of https://github.com/bisq-network/bisq/issues/4020#issuecomment-593108743

**Closed as completed by ripcurlx** 2020-03-11 08:21 UTC
Labels: was:duplicate
