### ISSUE TITLE
Inconsistent spent tx / depositTx is null when taking offer

### ISSUE THREAD

**Issue by julianknutsen** [bisq-network/bisq#3721] opened 2019-12-01 20:45 UTC
### Description

When taking an offer an error is presented and error logs display "Inconsistent spent tx:" and "depositTx is null".

Offer appears in "Open Trades" with no available actions.

After restarting Alice & Bob the option is available to move to "Failed Trades".

It looks like the multisig payout transaction from mediation on Bob (mediation payed out all to Alice) is the issue. I have 0% experience with that part of the codebase, but that is the common bad txn across runs.

#### Version

548a21775

### Steps to reproduce

100% repro over three runs with the following steps:

Alice - fullDaoNode |  Bob - (non-fullDaoNode || fullDaoNode)
1. Start localnet cluster
2. Run TestPad test case `Arbitration/Support Process: 002`
3. Run TestPad test case `Arbitration/Support Process: 009`
4. See failure when trying to take offer from Bob

### Expected behaviour

It works, or a more useful error message is presented.

### Actual behaviour

Error popup, log errors, and failed trade.

### Screenshots

**Error Logs**
![inconsistent_spent_tx](https://user-images.githubusercontent.com/8082291/69920022-0900e880-1438-11ea-9212-73114b0da79a.JPG)

**Transactions**
![inconsistent_spent_bob_txns](https://user-images.githubusercontent.com/8082291/69920025-09997f00-1438-11ea-9420-95c4e8f541b2.JPG)
![inconsistent_spent_alice_txns](https://user-images.githubusercontent.com/8082291/69920026-09997f00-1438-11ea-863d-6fb0c5b7917f.JPG)

**Funds Tab**
![inconsistent_spent_bob_funds](https://user-images.githubusercontent.com/8082291/69920027-0a321580-1438-11ea-8673-0879ab08440d.JPG)
![inconsistent_spent_alice_funds](https://user-images.githubusercontent.com/8082291/69920028-0a321580-1438-11ea-8c94-e149848ce7d6.JPG)

**Bob Trade Info**
![inconsistent_spent_bob_trade_info](https://user-images.githubusercontent.com/8082291/69920024-09997f00-1438-11ea-8227-ac358a387b71.JPG)

**After Restart:**
![inconsistent_spent_bob_after_restart](https://user-images.githubusercontent.com/8082291/69920023-09997f00-1438-11ea-8819-e5d522b6f677.JPG)

**After SPV Resync**
![inconsistent_spent_bob_after_spv_resync](https://user-images.githubusercontent.com/8082291/69920216-ea035600-1439-11ea-8524-c91e93df23ec.JPG)

#### Device or machine

Ubuntu 19.10

#### Additional info

[alice-bisq.log](https://github.com/bisq-network/bisq/files/3908695/bisq.log)
[bob-bisq.log](https://github.com/bisq-network/bisq/files/3908696/bisq.log)

**Comment by chimp1984** [comment] 2019-12-01 23:14
@julianknutsen Thanks for finding that! I could reproduce it. It seems BitcoinJ has problems with a tx where you do not receive anything. Still investigating what exactly is the reason and how we can fix that but for now the mediators should not make suggested payouts with one peer getting all and the other nothing to avoid that scenario until we have fixed it. They got informed to follow that until its solved.

**Comment by chimp1984** [comment] 2019-12-01 23:20
Ah we do not filter out the 0 BTC output!

mediated payoutTx:
```a059b45e02cc3ec7a5246c91634fe1e471b8f4e77508dc598de462f953fd1db3
     in   0[] PUSHDATA(72)[3045022100a9511f6e116da5e9dc086961e44fbe4d91e94654be14f0d98de0201c5e9c298b02207eef6f70b95b8042d8b4dc8263539660373510f6f03445eb0430b8a07f44daa701] PUSHDATA(72)[304502210091ae588103038937c558431da206988710eaa2b4675df8b1585aa42756f8358a022060f17384866a271396d1057e2affb116d13b578ee60f2462660de44aa1c232d401] PUSHDATA(71)[522103dee02e13b2484a2af6727371f8edc98fbe03e6727d844b15b45041a8b6db4a172102d6f58a3e89d1f6060e65b0a6c30daa21d54c90ba5c9f5b5a420af992b6a5995b52ae] 0.007038 BTC (703800)
          outpoint:65f3507e8a5b947c4566d18b49f25aac1e5cec04ff8af4a21e93b4d250adbfdc:0 hash160:b7221590dd29a428a70961e863b735bb06e2722f
     out  DUP HASH160 PUSHDATA(20)[390733579084df4539de897de4963325c45bcb7a] EQUALVERIFY CHECKSIG 0.007 BTC (700000) ScriptPubKey: 76a914390733579084df4539de897de4963325c45bcb7a88ac Address:mkiVSHsThWMzQzKhJdyWeGtusfrqpm8q8c 
     out  DUP HASH160 PUSHDATA(20)[809a6b272b4f0e741bcaefb90fc64e7f62ebcfd3] EQUALVERIFY CHECKSIG 0.00 BTC (0) ScriptPubKey: 76a914809a6b272b4f0e741bcaefb90fc64e7f62ebcfd388ac Address:msEwmoG66sv1MMLHpM4WXGc3r4V2VNwZ2x 
     fee  0.000038 BTC for 338 bytes (11 Satoshi/Byte)
     prps UNKNOWN```

**Comment by chimp1984** [comment] 2019-12-02 00:24
Fixed the moving to failed trade bug: https://github.com/bisq-network/bisq/pull/3726

**Comment by julianknutsen** [comment] 2019-12-02 00:49
I'm having a hard time keeping the bugs separate for each fix. Any other bug references I can look at for user-submitted ones?

Are there two separate issues here? 

1) not filtering 0 BTC output causes inconsistent spent tx error and popup/failure
2) trades that fail w/ inconsistent tx are incorrectly marked as failed trades?

**Comment by chimp1984** [comment] 2019-12-02 01:01
Added one: https://github.com/bisq-network/bisq/issues/3727
Just re tested and the bug was independent of the 0 BTC output issue.

**Closed as completed** 2019-12-02 10:09 UTC

**Comment by julianknutsen** [comment] 2019-12-02 22:12
Confirmed that the TestPad test case now passes on c2e8806d1
