### ISSUE TITLE
Performance improvement for UI (transfer FXML to code)

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#175] opened 2014-10-09 19:55 UTC
To improve performance we should convert FXML to code to avoid the FXML loading.

**Comment by ripcurlx** [comment] 2018-01-22 09:56
Isn't this kind of finished already?

**Comment by cbeams** [comment] 2018-01-24 10:15
@ripcurlx, why was this moved to `In Progress`? Want to make sure we're aligned about the semantics of that column. Thanks.

**Comment by ripcurlx** [comment] 2018-01-24 10:17
To be honest this was kind of a mistake on my side. Should be in Discussion.

**Comment by cbeams** [comment] 2018-01-24 10:21
No worries, thanks. FYI, there are still a number of FXML files. I can't remember if we ever made a decision on not doing this conversion, but the issue is ancient, I'd recommend closing it as `was:dropped`.

```
~/Work/bisq-network/exchange[master]
$ git ls-files | grep fxml$ | wc -l
      56
```

**Comment by ripcurlx** [comment] 2018-01-24 10:42
Yes, atm not all FXML files are replaced by code counterpart, so this issue is not done yet. The number of FXML files is still large, but they contain most of the time just root nodes.

**Comment by ripcurlx** [comment] 2018-01-24 10:42
But I also think that it has no value keeping this issue open like that.

**Closed as completed** 2018-01-24 10:44 UTC
Labels: in:gui, a:refactoring, was:dropped
