### ISSUE TITLE
relist Particl

### ISSUE THREAD

**Issue by SativaL** [bisq-network/bisq#2912] opened 2019-06-21 11:18 UTC
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 1. Asset name
Particl

### 2. Ticker
PART 
Unicode: U+20BD ₽ 

### 3. Block explorer URL
https://explorer.particl.io/

### 4. Additional technical requirements (yes/no)
no

### 5. Initial coin offering (yes/no)
no

**Comment by blabno** [comment] 2019-08-07 05:19
Is it ERC-20 token?
Is it privacy coin like monero?
Is it fork of any other coin?
What are the wallet address validation rules?

**Comment by LiteBit** [comment] 2019-08-07 16:19
Issue can be closed. Duplicate of https://github.com/bisq-network/bisq/pull/2919

**Closed as completed** 2019-11-12 17:26 UTC
Labels: was:dropped, in:altcoins
