### ISSUE TITLE
ConcurrentModificationException during network stress tests

### ISSUE THREAD

**Issue by ivilata** [bisq-network/bisq#443] opened 2016-05-10 09:48 UTC
While running network stress test (from branch `NetworkStressTests` in my Bitsquare fork), I'm getting spurious, random `ConcurrentModificationException`s. I'll be taking note of them in this issue so that they can be investigated later.

**Comment by ivilata** [comment] 2016-05-10 09:50
In `io.bitsquare.p2p.peers.PeerManager.removeReportedPeer`:

```
java.lang.Exception: java.util.ConcurrentModificationException
        at io.bitsquare.p2p.network.Connection$InputHandler.run(Connection.java:787)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.util.ConcurrentModificationException
        at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1563)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
        at io.bitsquare.p2p.peers.PeerManager.removeReportedPeer(PeerManager.java:321)
        at io.bitsquare.p2p.peers.PeerManager.handleConnectionFault(PeerManager.java:514)
        at io.bitsquare.p2p.peers.PeerManager.lambda$handleConnectionFault$17(PeerManager.java:504)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.bitsquare.p2p.peers.PeerManager.handleConnectionFault(PeerManager.java:504)
        at io.bitsquare.p2p.peers.PeerManager.onDisconnect(PeerManager.java:172)
        at io.bitsquare.p2p.network.NetworkNode$4.lambda$onDisconnect$1(NetworkNode.java:360)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at io.bitsquare.p2p.network.NetworkNode$4.onDisconnect(NetworkNode.java:360)
        at io.bitsquare.p2p.network.Connection.lambda$doShutDown$8(Connection.java:427)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
        at io.bitsquare.common.UserThread.execute(UserThread.java:56)
        at io.bitsquare.p2p.network.Connection.doShutDown(Connection.java:427)
        at io.bitsquare.p2p.network.Connection.shutDown(Connection.java:409)
        at io.bitsquare.p2p.network.Connection.shutDown(Connection.java:373)
        at io.bitsquare.p2p.network.Connection$SharedModel.shutDown(Connection.java:563)
        at io.bitsquare.p2p.network.Connection$InputHandler.run(Connection.java:739)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ivilata** [comment] 2016-05-11 07:12
Another similar one at `io.bitsquare.p2p.peers.PeerManager.printReportedPeers`:

```
java.lang.Exception: java.util.ConcurrentModificationException
        at io.bitsquare.p2p.network.Connection$InputHandler.run(Connection.java:787)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1545)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at io.bitsquare.p2p.peers.PeerManager.printReportedPeers(PeerManager.java:395)
        at io.bitsquare.p2p.peers.PeerManager.removeReportedPeer(PeerManager.java:315)
        at io.bitsquare.p2p.peers.PeerManager.removeReportedPeer(PeerManager.java:330)
        at io.bitsquare.p2p.peers.PeerManager.handleConnectionFault(PeerManager.java:520)
        at io.bitsquare.p2p.peers.PeerManager.lambda$handleConnectionFault$17(PeerManager.java:510)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.bitsquare.p2p.peers.PeerManager.handleConnectionFault(PeerManager.java:510)
        at io.bitsquare.p2p.peers.PeerManager.onDisconnect(PeerManager.java:172)
        at io.bitsquare.p2p.network.NetworkNode$4.lambda$onDisconnect$1(NetworkNode.java:360)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at io.bitsquare.p2p.network.NetworkNode$4.onDisconnect(NetworkNode.java:360)
        at io.bitsquare.p2p.network.Connection.lambda$doShutDown$8(Connection.java:427)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
        at io.bitsquare.common.UserThread.execute(UserThread.java:56)
        at io.bitsquare.p2p.network.Connection.doShutDown(Connection.java:427)
        at io.bitsquare.p2p.network.Connection.shutDown(Connection.java:409)
        at io.bitsquare.p2p.network.Connection.shutDown(Connection.java:373)
        at io.bitsquare.p2p.network.Connection$SharedModel.shutDown(Connection.java:563)
        at io.bitsquare.p2p.network.Connection$InputHandler.run(Connection.java:739)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

By enclosing `PeerManager.removeReportedPeer(Peer)` in a try/catch for the exception and logging the error (suggested by @ManfredKarrer), I got to get this:

```
09:05:42.723 [InputHandler-localPort=42072/port=55576] \
 ERROR io.bitsquare.p2p.peers.PeerManager - \
 concurrent modification at PeerManager.removeReportedPeer(peer), \
 current thread InputHandler-localPort=42072/port=55576
```

The issue is knowing what other thread is accessing the `reportedPeers` object.

**Comment by ivilata** [comment] 2016-05-11 08:21
A different one at `io.bitsquare.storage.FileManager.saveToFile`:

```
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
    at java.util.HashSet.writeObject(HashSet.java:286)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
    at io.bitsquare.storage.FileManager.saveToFile(FileManager.java:194)
    at io.bitsquare.storage.FileManager.saveNowInternal(FileManager.java:173)
    at io.bitsquare.storage.FileManager.lambda$new$0(FileManager.java:67)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
19:54:48.274 [Save-file-task-9018] ERROR io.bitsquare.storage.FileManager - Error at saveToFile: null 
19:54:48.277 [Save-file-task-9018] WARN  io.bitsquare.storage.FileManager - Temp file still exists after failed save. storageFile=/tmp/bsqNST/peer-000096/db/PersistedPeers 
```

**Comment by ManfredKarrer** [comment] 2016-05-11 11:02
hm, not sure if that was i was referring in the last mail. i assume that is also related to a threading issue form the test setup.
i think the error i saw sometimes was another.

**Comment by ivilata** [comment] 2016-05-11 17:53
Another one also related with reported peer removal:

```
19:49:00.944 [Timer-0] ERROR io.bitsquare.common.FrameRateTimer - null
java.util.ConcurrentModificationException
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1545)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.bitsquare.p2p.peers.PeerManager.removeTooOldReportedPeers(PeerManager.java:341)
        at io.bitsquare.p2p.peers.PeerManager.lambda$doHouseKeeping$0(PeerManager.java:198)
        at io.bitsquare.common.FrameRateTimer.run(FrameRateTimer.java:32)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at io.bitsquare.common.MasterTimer$1.lambda$run$0(MasterTimer.java:21)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
        at io.bitsquare.common.UserThread.execute(UserThread.java:56)
        at io.bitsquare.common.MasterTimer$1.run(MasterTimer.java:21)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

(I'm also looking at the test setup that @ManfredKarrer mentions which relates to setting the `UserThread` executor.)

**Comment by ivilata** [comment] 2016-05-11 19:02
I set a single thread executor in the test as suggested by @ManfredKarrer:

```
UserThread.setExecutor(Executors.newSingleThreadExecutor());
```

All `ConcurrentModificationException`s seem to have gone away, but the test needs a lot more open files (that can be provided via `ulimit` or `prlimit` in GNU/Linux). If they don't appear again, I'll close the issue. Thanks!

**Comment by ivilata** [comment] 2016-05-12 09:07
Ummm, `saveToFile()` concurrency errors still happen with the new executor…

**Comment by ManfredKarrer** [comment] 2016-05-25 11:51
I think those concurrency issues are caused by the test setup. So I will close it for now. If we find out it is also happening the in the app or seed node please re-open.

**Closed as completed by ManfredKarrer** 2016-05-25 11:51 UTC
