### ISSUE TITLE
Trigger price truncation of prompt text not working

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#5189] opened 2021-02-12 10:06 UTC
I just recognized in the German translation that the truncation of the new trigger price feature is not configured properly. Also the provided text is not properly translated (I'll take care of this on Transifex myself).

![Bildschirmfoto 2021-02-12 um 11 02 44](https://user-images.githubusercontent.com/170962/107754747-3591df00-6d22-11eb-824b-0b504e96c747.png)

**Comment by forcryptos** [comment] 2021-02-21 16:31
I am actively exploring the code to make a fix for this, if someone is already working on this, let me know and I will find another issue.

I will be testing most of the fields containing text to see if the do not wrap the inner text.

**Comment by ripcurlx** [comment] 2021-02-22 08:33
> I am actively exploring the code to make a fix for this, if someone is already working on this, let me know and I will find another issue.
> 
> I will be testing most of the fields containing text to see if the do not wrap the inner text.

Feel free to take it. Right now I only fixed it by adapting the German translation. But this issue might still exist in other languages.

**Comment by forcryptos** [comment] 2021-02-22 18:59
I was thinking about setting up truncation on the boxes but I realized its just a label overlay over the text box. I guess I will do a quick check in the different languages to see if the problem is major over multiple languages

**Comment by alvasw** [comment] 2021-12-08 16:48
I'm working on this. Just letting everyone know.

**Comment by alvasw** [comment] 2021-12-08 19:26
This turned out to be tricky. There are two bugs:
1. The shield icon is drawn on top of the prompt text. (I fixed this already!)
2. The default TextField class (InfoInputTextField inherits from it) class aligns the prompt text to the right by default. Changing the alignment to the left does not solve the problem because the text is still too long.

There are multiple solutions:
1. Make the text boxes larger so that the prompt text is shown fully. In this case, we have to apply the same size to the text box above (the larger width out of both); otherwise, it looks weird.
2. Truncate the text, but I'm not sure if this makes sense in every language.
3. Use shorter prompt texts (like the fix you applied to German)

How it looks after solving problem number one:
![bisq_prompt_text_shield_fix](https://user-images.githubusercontent.com/95712046/145271263-db085a08-df06-40ee-9eac-5a86f92ecc8d.png)

**Comment by alvasw** [comment] 2021-12-13 19:17
Sorry, I won't complete this. After chatting with a team member I decided to work on Bisq 2.0.

**Closed as completed** 2022-03-21 10:01 UTC
Labels: in:gui, good first issue
