### ISSUE TITLE
Take Offer page does not save Trading Account

### ISSUE THREAD

**Issue by gdvine** [bisq-network/bisq#1064] opened 2017-12-05 15:59 UTC
v 0.6.1
Mac OS X 10.12.6

Steps to reproduce:
1. Take an offer and see Take Offer page
2. Select a Trading Account (not your default)
3. Go to a different page (settings, Funds anything)
4. Come back to Take Offer page

Expected behavior:
Take Offer page still has the same Trading Account selected as before

Observed behavior:
Take Offer page Trading Account dropdown reverts to default option

**Comment by ripcurlx** [comment] 2018-12-20 09:13
Closing as complete. Can't reproduce with 0.9.1.

**Closed as completed by ripcurlx** 2018-12-20 09:13 UTC
