### ISSUE TITLE
Timeout when creating sell offer

### ISSUE THREAD

**Issue by llhoppy** [bisq-network/bisq#1087] opened 2017-12-12 14:23 UTC
Hi
I have had 2 instances of a timeout error when creating a sell offer. Manfred is aware of the error from my forum post.

 [bisq.log](https://github.com/bisq-network/exchange/files/1551899/bisq.log)
[bisq_1.log](https://github.com/bisq-network/exchange/files/1551900/bisq_1.log)
![screenshot_2017-12-12_13-28-50](https://user-images.githubusercontent.com/2623245/33889376-cc0f8f5c-df47-11e7-8cde-23c964491536.png)

**Comment by ottohotz** [comment] 2017-12-16 23:21
i had the same (or similar) issue when creating a buy order. what about the lost BTC?
[bisq.log](https://github.com/bisq-network/exchange/files/1565170/bisq.log)

**Comment by lordbah** [comment] 2017-12-18 06:23
Same error when creating a sell offer. Same question "where's the bitcoin?". Didn't see anything obvious in the log (hesitant to post it without redaction). v0.6.1. Funds may not have "left the wallet", but Reserved and Locked are both 0 and Available balance has been reduced by the amount required for the offer (funded from bisq wallet), so they look "gone". I see a transaction where trading fee + mining fee were sent somewhere. No other transactions.

After restart, Available balance now does include the amount I was trying to sell. So that's some comfort I guess. Looks like only the fees are lost.

An error occurred when placing the offer:

A timeout occurred at publishing the offer.

No funds have left your wallet yet.
Please restart your application and check your network connection.

**Comment by ManfredKarrer** [comment] 2017-12-18 11:24
I am working on it and there will be soon a new release.

**Comment by montvid** [comment] 2017-12-19 09:32
I had the same error. I just clicked again and it went through. I was happy in the end but the error at first was really scary!

**Comment by montvid** [comment] 2017-12-19 09:41
Omg so I was charged 2 times? I counted my btc and it seems yes i was. How can I get my bitcoin back? Do you need my bisq log?

**Comment by KanoczTomas** [comment] 2017-12-19 10:00
I had the same error, but when trying to take the offer. Yeah fees were taken 2 times away. I can append the log as well if that helps.

**Comment by Yonnis01** [comment] 2017-12-19 10:21
Hey "montvid", Thank You for making me aware that you had the same problem and I lost BTC every time I tried to take an offer, and the system came back with the ERROR massage and I it didn't take my offer but after all I was charged. First time it happened was on 12/14/2017 at 6:21:11AM when It withdrawn by ERROR 0.001084 BTC and yesterday morning 12/18/2017 it happened again 5 (five) times between 6:38:32 AM and 7:36:09 AM for a combined total of 0.010165 BTC. So, the 6 ERRORS together are 0.011249 BTC which at $18,500 per BTC is about $208 in losses withdrawn from my BISQ Wallet for no reason... I hope that Manfred will fix this issue and reimburse us for this system glitch... Respectfully, YS

**Comment by montvid** [comment] 2017-12-19 10:50
I dug deeper into this with the block explorer. The bug is that bisq instead of 1 transaction does >1 when processing 1 order . You can check in the block explorer. In my case it did 2 transactions so i had to pay 2x miner fees and 2x bisq fees. Now bisq fees can be returned by bisq but it is a drop in the bucket comparing to the miner fees lost to execute the transactions - these fees bisq can't return only compensate if possible.

**Comment by montvid** [comment] 2017-12-19 13:19
@ManfredKarrer I don't see bisq downloads being disabled on the main site because of this critical bug! Who knows how many people will download 0.6.1 and loose btc! Why there is no warning on the main site to stop using 0.6.1? I don't understand the reaction of devs is it not a priority to stop users loosing their btc?

**Comment by cbeams** [comment] 2017-12-19 13:20
Stay tuned, everybody, I'll post an update on this issue shortly.

**Comment by lordbah** [comment] 2017-12-20 01:34
Had same error dialog creating sell offer for Dash. But by the time I copy/pasted errors into this issue, it claims it *did* publish the offer. Nothing in the log marked ERR at the time but there is

[DNS seed lookups] WARN  i.b.n.DnsLookupTor: Error resolving dnsseed.dashpay.io. Exception:
io.bisq.network.DnsLookupException: tor host is unreachable(host=dnsseed.dashpay.io) 
[PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed dnsseed.dashpay.io: failed to look up: org.bitcoinj.net.discovery.PeerDiscoveryException: io.bisq.network.DnsLookupException: io.bisq.network.DnsLookupException: tor host is unreachable(host=dnsseed.dashpay.io)

**Comment by cbeams** [comment] 2017-12-20 09:25
UPDATE: **if you are someone who has lost a maker or taker fee due to the timeout issues being discussed here, please contact me directly** via private message on the Bisq forum, private message via Bisq's Slack, or via email at chris@beams.io. My PGP key is publicly available for those who wish to encrypt the latter.

**Comment by tr37ion** [comment] 2017-12-22 01:52
@cbeams @ManfredKarrer Well, this could be a case for using Keybase over Slack or PM forum posts  as Keybase offers PGP encryption, verification and directly links that with Github accounts and adds a encrypted chat to Github accounts, too.

**Comment by cbeams** [comment] 2017-12-22 10:43
I'm fine with using Keybase, @tr37ion (and anyone else who wants to contact me that way).

**Comment by cbeams** [comment] 2017-12-23 10:57
I am closing this issue. If you have been affected by this issue, and you have not already done so, please contact me directly at chris@beams.io, and we'll get this worked out together. Please reference this issue when you do. Thanks. /cc #1044

**Closed as completed by cbeams** 2017-12-23 10:57 UTC

**Comment by ottohotz** [comment] 2017-12-23 12:15
Hey,
as I already commented on the topic and posted the logfile, I also lost the
trading fees.
Do I get these fees back? What do you need for a refund?
Thanks!

2017-12-23 11:57 GMT+01:00 Chris Beams <notifications@github.com>:

**Comment by cbeams** [comment] 2017-12-23 12:19
@ottohotz, please send me an email at the address I posted in my last comment, and include the following information, or as much of it as you can provide:

 - screenshot of your `Portfolio->Failed` screen
 - screenshot of the trade details / info (i) screen from any failed trade
 - paste the transaction hashes (maker / taker / deposit transactions) from that info screen
 - paste the transaction hashes of any other transactions you believe are relevant to this issue
 - screenshot of your `Funds->Send funds` screen
 - screenshot of your `Funds->Transactions` screen
 - specify the amount of BTC you believe you should be reimbursed

Please understand that due to the Christmas holidays and an upcoming conference, it may take me some time to get back about this. I will do my best to handle it as quickly as possible, though, and rest assured that we'll get this worked out together. Thanks for your patience!

**Comment by Yonnis01** [comment] 2017-12-23 22:00
HUGE NETWORK/Confirmation Delay Problems!!!

On December 19th at 1:18:33 AM (Trade ID 4159602) and at 1:23:29 AM (Trade
ID GJ3fBVD), I placed 2 offers to purchase BTC which as of noon on December
23rd 2017 (5 days later) are still NOT Confirmed by the system and as such,
DID NOT give me the option to Start the payment and conclude this
transactions...

At this point in time, with just 1 day and 12 hours left, even if those 2
transaction will mysteriously get confirmed by the system, there is
absolutely NO POSSIBLE way for the payments to be stated, submitted,
processed and received by the seller before the 7 days deadline.  Today is
Saturday 12/23 and for the next 2 days, the 24th and 25th ALL the banks are
closed...

My question is, what are my options at this point in time?

Do I have to wait another 36 hours for this offer to expire and get back my
locked deposit of 0.06 BTC and start a new offer?

Please advise!

NOTE: See the attached 2 screen snapshots of the 2 orders in questions
which with only ONE DAY and 10 hours (left which is over the weekend) are
still waiting for the transaction Confirmation before I can do anything
else.

Respectfully,

Yonni S

**Comment by Yonnis01** [comment] 2017-12-24 00:43
A couple of days ago I sent this request for refund of 0.010165 BTC
withdrawn from my account several times when I placed an Offer that didn't
go through and I got an ERROR message but I didn't get any answers back so
far...

Can anyone help?

Respectfully,


Resending the message:



Hello Chris or anyone else that can help,

Thank You for contacting us about our losses and trying to help us.

Yes, I lost BTC every time I tried to take an offer, and the system came
back with the ERROR massage and it didn't take my offer but after all I was
charged anyway...

First time it happened was on 12/14/2017 at 6:21:11AM when they withdrawn
by ERROR message 0.001084 BTC and went to address
18GzH11T5h2fpvUoBJDub7MgNJVw3FfqQ8    and on the morning of 12/18/2017 it
happened again 5 (five) times at 6:38:32 AM, 6:42:11 AM, 6:56:36 AM,
7:11:25 AM and 7:19:52 AM for a combined total of 0.010165 BTC and all of
them went to the following address: 1DDZW8jBJKFGPh1VAB8akP1oZkFJsYFgAk

So, the 6 ERRORS together are 0.011249 BTC which at $18,500 per BTC is
about $208 in losses withdrawn from my BISQ Wallet for no reason...

So, let me know if you need any other info from me and I hope that you or
Manfred will fix this issue and reimburse me for this system glitch...

Respectfully,

*Yonni Simion*


*YONNI SIMION, Realtor, ABR, GRI*
*West USA Realty*

*Direct: 602.791.4499*
*www.AZHomesHunter.com <http://www.AZHomesHunter.com>*

Confidentiality Notice: The information contained in this electronic e-mail
and any accompanying attachment(s) is intended only for the use of the
intended recipient and is non-public in nature and may be confidential
and/or privileged. If any reader of this communication is not the intended
recipient, unauthorized use, disclosure, dissemination or copying is
strictly prohibited, and may be unlawful. If you have received this
communication in error, please immediately notify the sender by return
e-mail, and delete the original message and all copies from your system and
promptly destroy any copies made of this electronic message. Thank you.

**Comment by tr37ion** [comment] 2017-12-24 02:16
@Yonnis01 Not sure, it looks like you did quote yourself in two posts, or? I have problems to understand what you are saying. Can you delete one post and put everything together in just one post? Maybe that helps.

**Comment by Yonnis01** [comment] 2017-12-24 05:30
NO, please don't close this issue/file because my problems are not resolved!!!
And YES tr37ion, I did sent 2 different posts (one several days ago and one earlier today) because I do have 2 different problems:
1st. The 1st post was about the ERROR on the system and being charged a total of 0.010165 for 5 different offers I made and each one of them, before it went through, it came back as ERROR but each time money were take out from my account. All the details about that were sent to you in my 1st post which I sent a couple of days ago and, because I didn't get any answers, I sent it again earlier today.
2nd. The 2nd post was the 2 offer I made that finally went through, but after 5 days and a half, neither one received any confirmation and I wasn't able (it didn't allow me) to start the payment. Please see the 2 attached PDFs with screen shots of the BISQ system pages where, as of earlier today, with just 36 hours left, I has still waiting for the confirmations of the transaction to go through in order to start my payment... 
I looks like after all, my deposit of 0.06 BTC was locked and held for this two offers, but the confirmation for Sellers BTC it never came, or at least it didn't came as of noon today which is to late to finalize this transaction. I had no idea that your system has so many problems and is so faulty... We need to post this somewhere and to make everyone aware of all this issues I've been having I've been having with Bisq within the last week... 
I did used your system 3 other times last week and everything went through smoothly, so I know that is nothing wrong that I did on my side to slow down the process, but your Bisq system it has (or had) several issues with withdrawing funds with Error messages without the offer going through as mentioned on my 1st post from several days ago.
Now I need your help and with my last 2 offers which I made over 5 and 1/2 days ago and for which I still didn't receive confirmations as of noon today and which made it impossible on my end to send the payment...
Can you please help with all this mess?
I do need/expect answers and resolutions for both of my posted problems, but especially for my 2nd post with the 2 Offers transactions ID# 4159602 and ID# GJ3fBVD which are still waiting for confirmation for starting my payment but less than 34 hours to be processed and to be finalised while tomorrow is Sunday and Monday is Christmas and all the banks are closed... 
Please advice ASAP...   Thank you!
Respectfully,
Yonni S
    On Saturday, December 23, 2017, 7:16:29 PM MST, tr37ion <notifications@github.com> wrote:  
 
 
@Yonnis01 Not sure, but did you actually quote yourself in two posts? I have problems understand what you want to send to whom. Or was it planned as PM? Can you delete one post and put everything together in one post? Maybe that helps.

**Comment by cbeams** [comment] 2017-12-24 10:03
@yonnis01, your trades that are stuck on confirmation can be taken to arbitration after the trading window expires. Please have patience, it's Christmas time and people (including myself) are with family and have limited availability.

With regard to your failed trades and lost fees, we'll work this out together. Please follow my instructions above and send me an email. GitHub is not a good place to deal with this sort of thing, as it requires sharing all kinds of transaction details.

Thanks.

**Comment by ottohotz** [comment] 2018-01-05 20:13
i'm still waiting for an answer or a refund.... the bug happened almost 3 weeks ago :-(

**Comment by montvid** [comment] 2018-01-05 20:22
@cbeams is working on it I heard some comments on github. Well he did not reply to my latest email but never mind. Too bad he closed the issue when the problem still persists. I guess he wants to make a batching send of btc to all of us at once to save on blockchain space. Worth the wait - no worries.

**Comment by cbeams** [comment] 2018-01-05 20:49
@montvid is correct re batching the payments. It's been an extraordinarily busy few weeks for us and I'm setting aside as much time as necessary next week to work through these reimbursements. Thanks everyone for your patience and support. We'll get this worked out.

**Comment by cbeams** [comment] 2018-01-12 13:30
@Yonnis01, please contact me as soon as possible at chris@beams.io. I have important information about your trade ID `GJ3fBVD`. Thanks.

**Comment by cbeams** [comment] 2018-01-12 13:46
@keo-bisq, please check your arbitration history for trade `4159602` and get in touch with @Yonnis01 as necessary. Search upward in this GitHub issue for context on that trade and `GJ3fBVD` (which is mine).

**Comment by keo-bisq** [comment] 2018-01-13 16:01
@Yonnis01, please contact me, Keo, at stibor@protonmail.com, since we might lose contact in the app. I arbitrate 4159602.

**Comment by Yonnis01** [comment] 2018-01-15 08:03
Hello Keo,
I was expecting for someone to reach me and get this issue solved and release my funds for over 3 weeks...On Dec 19th I was in need of some BTC to purchase another altcoin which had a big correction dip at that time. I used Bisq previously without any problems and I was hopping that this transaction will go through, like before, within 3 to 5 days to accomplish my goal, but that did not happened this time... :(
Last email I sent you guys asking for help was 2 days before Christmas, on Sat, Dec 23rd 2017 when my trade was already 4 and 1/2 days old and I still didn't have the confirmation from the Blockchain to proceed to the next step and start the payment processing. That on on Saturday 12/23, and at that point, even if it would have been confirmed, I would have been left with less than 37 hours to process the payment, but that was on Sunday 12/24 and then Monday 12/25 Christmas Day, which would have been impossible to work with my bank and process the SEPA payment because everything was closed til Tuesday 12/26 and my was Monday 12/25 at 1:18 am... So, it looks like is no one's fault that the Blockchain (or the Bisq system) did not confirm that transaction within the time that would have been possible for this to transactions to go through with the payment processing and as result, please unlock my 0.06 BTC to my available account asap. To support my claim, attached you'll find the 2 screen shoots that I took for both transaction on Saturday 12/23, after more than 4 and 1/2 days of waiting and when I realized that they can not be performed into the timing allowed and to fulfill the need I had at that time for the 0.375 BTC in question. Please let me know how soon this issue will be solved. Thank you!
Respectfully,
Yonni S    On Saturday, January 13, 2018, 9:01:24 AM MST, keo-bisq <notifications@github.com> wrote:  
 
 
@Yonnis01, please contact me, Keo, at stibor@protonmail.com, since we might lose contact in the app. I arbitrate 4159602.

**Comment by cbeams** [comment] 2018-01-15 10:59
@Yonnis01, please contact me in the Bisq application regarding trade `GJ3fBVD`. I have been unable to communicate with you there, and I am not sure you were ever able to see my messages. Please also send me an email at chris@beams.io to let me know when you've attempted to contact me in-app, to make extra sure we don't miss each other. Your counterparty in this trade is very patient, and is waiting for you and I to work it out. Thanks!

**Comment by Yonnis01** [comment] 2018-01-16 07:31
Hello Chris,
I'm not very techie and I don't know how to contact you in the Bisq application... I was already contacted/emailed by Keo yesterday 1/14/2014 and I also sent him this email as well... I don't know which one of you is the arbitrator for this 2 transactions...In fact I've been expecting for someone to reach me and get this issue solved and release my funds for over 3 weeks... :(
So, this are the facts:On Dec 19th I was in need of some BTC to purchase another altcoin which had a big correction dip at that time. I used Bisq previously without any problems and I was hopping that this transactions ( 4159602 & GJ3fBVD) will go through like some other I did before, within 3 to 5 days to accomplish my goal, but that did not happened this time... :(
Last email I sent you guys asking for help was 2 days before Christmas, on Sat, Dec 23rd 2017 when my trades were already 4 and 1/2 days old and I still didn't have the confirmation from the Blockchain to proceed to the next step and start the payment processing. That on on Saturday 12/23, and at that point, even if it would have been confirmed, I would have been left with less than 37 hours to process the payment, but that was on Sunday 12/24 and then Monday 12/25 Christmas Day, which would have been impossible to work with my bank and process the SEPA payment because everything was closed til Tuesday 12/26 and my was Monday 12/25 at 1:18 am... So, it looks like is neither Buyer or Seller's fault that the Blockchain (or the Bisq system) did not confirm those transactions within the time that would have been possible for this to transactions to go through with the payment processing and as result, please unlock my 0.06 BTC to my available account asap. To support my claim, attached you'll find the 2 screen shoots that I took for both transaction on Saturday 12/23, after more than 4 and 1/2 days of waiting and when I realized that they can not be performed into the timing allowed and to fulfill the need I had at that time for the 0.375 BTC in question. Please let me know how soon this issue will be solved. Thank you!
Respectfully,
Yonni S
    On Monday, January 15, 2018, 3:59:22 AM MST, Chris Beams <notifications@github.com> wrote:  
 
 
@Yonnis01, please contact me in the Bisq application regarding trade GJ3fBVD. I have been unable to communicate with you there, and I am not sure you were ever able to see my messages. Please also send me an email at chris@beams.io to let me know when you've attempted to contact me in-app, to make extra sure we don't miss each other. Your counterparty in this trade is very patient, and is waiting for you and I to work it out. Thanks!

**Comment by cbeams** [comment] 2018-01-16 08:15
@Yonnis01, please go to into Bisq, and navigate to `Support->Support Tickets` and click on `GJ3fBVD`, where we can discuss next steps with that trade in privacy. Thank you.

If you are unable to do this for some reason, please contact me via email at chris@beams.io.
