### ISSUE TITLE
Incorrect formatter for BSQ

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#3675] opened 2019-11-24 17:40 UTC
Seems in the master version some of the latest PRs have introduced a bug with the formatter:

At DAO voting the BTC formatter is used instead of the BSQ formatter:
<img width="323" alt="Screen Shot 2019-11-24 at 12 39 08" src="https://user-images.githubusercontent.com/54558767/69498599-7f8d6b80-0eb7-11ea-9965-c335350b6404.png">

Probably there are more such issues.

**Comment by julianknutsen** [comment] 2019-11-24 22:17
Duplicate of #3672

**Closed as completed** 2019-11-25 11:28 UTC
