### ISSUE TITLE
Bisq - Error: possiblePaymentAccounts.isEmpty()

### ISSUE THREAD

**Issue by noideaaboutnothing** [bisq-network/bisq#3601] opened 2019-11-12 20:46 UTC
-->

### Description

 When clicking on a "suitable" offer (buy BTC) error msg appeares....

'Error: possiblePaymentAccounts.isEmpty()'

It is reproduceable on two different pc's (fresh installation) when chosing the same offer. Picking another offer (sometimes) works.

### Screenshots

screenshots and log file attached

[bisq_log.txt](https://github.com/bisq-network/bisq/files/3838151/bisq_log.txt)
![issue screenshot](https://user-images.githubusercontent.com/31408886/68709352-d0d35c00-0595-11ea-8c71-8a210280a62f.PNG)

#### Device or machine

x86 and x64

**Comment by rafaelpac** [comment] 2019-11-13 11:32
I get the same here. After getting it, I can't open any other order.

**Comment by rafaelpac** [comment] 2019-11-13 11:39
duplicate of #3537

**Comment by rafaelpac** [comment] 2019-11-16 21:23
This problem is caused only in offers that have min-max ranges.
Pull request #3625

**Closed as completed** 2019-11-18 15:00 UTC
