### ISSUE TITLE
GUI bugs

### ISSUE THREAD

**Issue by riclas** [bisq-network/bisq#382] opened 2016-04-15 19:00 UTC
1) i can't see the 3 top offers of the order book. it shows 2, then some sliders show up but i can't move them. remove the sliders. make the table size fixed for the number of offers.

2) don't let the window be resizeable after it reaches the maximum compact limit. it will overlap on the gui

see both problems in this screenshot: http://imgur.com/PPYTKog

3) In Account -> National currency accounts -> create new account: if you click one of the input fields (Account nr. for example) and then click outside of the window on another application or maximize the window, the "empty input is not allowed" message remains on the same place
see here: http://imgur.com/6M8jdNk

4) Account name should be the first field in "Create new account" IMHO

5) It's weird to have the "create new offer for buying bitcoin" and selling, respectively,  on the buy BTC and sell BTC screens. To me it makes sense the other way around, i.e. to create a sell offer on the buy screen and vice versa. But even that is confusing...
I would suggest removing the buttons from the buy btc and sell btc windows, create one big "Create offer" button and then let the person specify if they are buying or selling btc.

And btw i think a lot of people will create offers by mistake and be pissed off at paying the fee for creating an offer if they make a mistake. Furthermore, If the price fluctuates, cancelling and creating new offers becomes expensive. I know you are working on the percentage offers that should solve this issue, still changing percentages will require cancelling and reissuing offers, which will still be expensive :\

**Comment by ManfredKarrer** [comment] 2016-04-15 21:56
Hi @riclas 
Thanks for all the input!

1: Do u used the latest verion (0.4.1)? If so could u send me a screenshot of the complete screen and info about your OS. If u use windows do you have system wide font scaling activated (125%). But that should be fixed in the current version.
2: Yes the window size is a known issue. I dont want to limit it for too large as it would not fit on small sceens. Need to support scrolling in each screen what is a bit of work...
3: Also a known issue. I basically would like to change that input validation system completely. So you dont get feedback on focus-out but when you want to click the button for confirming.
4: Will consider to change that
5: I know that buy/sell thing is confusing as it is mirrored. If you want to buy btc you are interested to see the sell offers. I try to keep it always from the perspective of the user: If you want to buy btc u go to the buy screen and either take an (sell) offer or you create a (buy) offer.
Offer fee is currently 0.0005 btc just a bit above the mining fee. Editing offer is on the todo list. Soon there will come % based price (% distance from market price). I already implemented it but needs good testing as it was a bigger change and a bit risky so soon before beta, but prob. will get published the next days. Would appreicate if you could help testing when its out!
The offer fee is required as protection against spam and market manipulation.

**Comment by riclas** [comment] 2016-04-16 01:49
1) yes i am using 0.4.1. Windows 10, 100% font scaling. here's the full table: http://imgur.com/bzmA3T3

5) Even though i understand your point, I still think unifying the new offer options into one screen would greatly improve usability.

Editing offers would solve my last issue.

**Comment by ManfredKarrer** [comment] 2016-04-16 09:32
Re 1: Need to investigate and reproduce the issue...
Re 5: Will consider UI changes for later releases. Atm it would be too much effort.
The edit feature is definitely on the road map.

**Comment by ManfredKarrer** [comment] 2016-04-16 10:42
Re 1: I though I had the layout fix already deployed in 0.4.1 but it is not in. So in the next version that is fixed.

**Comment by JoshLambda** [comment] 2016-04-20 15:33
About 5) this one is tricky and in my opinion "Top 3 offers for buying bitcoin" does _not_ mean buy offers.  
It's like in "Top 3 shops for buying food" meaning a service "for _you_ to buy X" and so this should rather be above sell offers. A way to avoid ambiguity could simply be "Top 3 buy offers".  
I think this matter is probably _more important than it seems_ because it could make things confusing to first time users. Just my 2 cents and ofc I would suggest to get other opinions as well.

**Comment by ManfredKarrer** [comment] 2016-04-20 15:43
Yes that wording is quite difficult to get right. I changed it often after user feedback but many have differnet opinions :-). I plan to do a review about all text with a native speaker once I have time for that. For now I perfer to keep it as it is because it is used in many places like that.

**Comment by JoshLambda** [comment] 2016-04-20 15:47
That makes sense, awesome work by the way. :)

**Comment by ManfredKarrer** [comment] 2016-04-28 18:54
Close that as partly fixed and othere parts are discussed in the forum.

**Closed as completed by ManfredKarrer** 2016-04-28 18:54 UTC
