### ISSUE TITLE
possiblePaymentAccounts.isEmpty bug | Take Offer to buy BTC Bug

### ISSUE THREAD

**Issue by Conza88** [bisq-network/bisq#3540] opened 2019-11-02 02:41 UTC
### Description

possiblePaymentAccounts.isEmpty()

#### Version

v1.2.2

### Steps to reproduce

Clicking accept / take an offer to buy BTC - Australia section. Other 5 days since verified signing. Have taken offers before, and no problems. 

### Expected behaviour

Accept the trade, and continue from there. 

### Actual behaviour

Error pops up. possiblePaymentAccounts.isEmpty()

#### Device or machine

Windows 10.

#### Additional info

[bisq - bug.txt](https://github.com/bisq-network/bisq/files/3800070/bisq.-.bug.txt)

**Comment by freimair** [comment] 2019-11-11 14:55
duplicate of #3537

**Closed as completed by freimair** 2019-11-11 14:55 UTC
