### ISSUE TITLE
Transaction stuck, can't open mediation because "deposit transaction" is missing

### ISSUE THREAD

**Issue by polaris1205** [bisq-network/bisq#4872] opened 2020-12-02 02:29 UTC
### Description

I have a transaction that has been stuck since November 7, and when I try to open a support ticket, this is the error message it shows (See attached image below).

Also note, the trade period is stuck at 4 days, it doesn't count down.

#### Version

1.4.2 when the error occured.
Currently running 1.5.0

### Steps to reproduce

I don't know how to reproduce this, but this is what happened:
1) When I initially took the offer to buy, BISQ crashed suddenly. Afterwards, an error message prevented me from initiating the application.
2) Upon reseacrch, I realized my wallet got corrupted, so I deleted the wallet file, reopened BISQ, and finally used the seed to restore. 
3) My wallet balance now showed 0 BTC (I had a balance since I transferred BTC for the deposit).
4) I tried to do an SPV re-sync, but after leaving it on for days, I gave up. (My processor was also running very hot/ max capacity)
5) I imported the wallet seed into Electrum, and was able to salvage the BTC I had transferred. But the transaction on BISQ has remained stuck ever since, and the seller still has his BTC locked in there.

### Screenshots

![Capture](https://user-images.githubusercontent.com/66457627/100819738-bd9e6300-341a-11eb-8adb-d839d41191ad.JPG)

#### Device or machine

HP-Envy-15 2040nr (2012)
Windows 7

**Comment by chimp1984** [comment] 2020-12-03 16:38
Can you post the maker fee tx id and taker fee tx id and a screenshot of the trade details window (blur out private data)?

**Comment by polaris1205** [comment] 2020-12-05 01:16
Maker fee Transaction ID a01eab4dc345dda1c6763c29e8bc0fd95fd2018e00496beb5edb5ab8dd0e2e84
Taker Fee transaction ID f546eb3aa82af6d396e68cc5e44aaec57e5e07bb7a9a7e9024c108a8bfad5aa4

![Capture](https://user-images.githubusercontent.com/66457627/101229306-91c6eb80-366d-11eb-8384-cf2ff43af4ec.JPG)

**Comment by chimp1984** [comment] 2020-12-07 16:04
The taker fee tx is not found in the mempool. So there is no deposit tx either. Can you move the trade to failed trades?

**Comment by polaris1205** [comment] 2020-12-08 03:35
I can't move it to failed trades, and neither can the seller. The usual icon that shows up on the right side is not there. Is there any other way to move it to failed trades besides the icon?

**Comment by chimp1984** [comment] 2020-12-08 16:34
I will have a look why its not shown the button to move. If u have no open trades you can go to the db folder in the data dir (open it vai account/backup -> button to open data dir) and delete the PendingTrades file. That will delete it (not move it). If you have any unconfirmed txs in funds/tx check if those are visible in a blockexplorer (click on it) - if not then do a spv resync.

**Comment by chimp1984** [comment] 2020-12-08 16:34
Can you tell your peer to read that msg here as well?

**Comment by polaris1205** [comment] 2020-12-09 02:00
ok, I have a pending transaction that should clear in a day or two, and then I will follow your steps. The seller has the link to this issue. I will send a message as well just in case. Will check in here again after. Thanks!

**Comment by chimp1984** [comment] 2020-12-10 18:42
With 1.5.1. I think you should be able to move the tx.

**Comment by polaris1205** [comment] 2020-12-12 05:26
Well, deleting PendingTrades indeed worked as you said it would. I did the SPV re-sync and all seems to be ok. The transaction is completely gone now; there is no record of it, as if it had never happened. I am satisfied with the result, but I am not sure if the seller was able to recover their BTC.

**Comment by pazza83** [comment] 2020-12-12 16:05
Hi @chimp1984 

I have the same problem. 

Trade is stuck since 29 September in my open trades. Countdown not moving.

Trade has been through mediation and settled, I think buyer ended up making payment, but I am unable to move it to failed trades. 

I have other open trades so cannot delete the Pending Trades file.

Maker fee: 344f9456dec3cfb88d06bd5ee029e9b9c2e0c2c0a2396b0331a95f66e2906b6a

Taker fee: 837f01d946c7b1dd170a455a25c709894cf418235441f695b68c9d2ad664437d

Delayed payout: 2e7fcd9310708bbcee0c8472a1922e85e44afbf674bf49948b722d7d5de416e8

How can I move it do failed trades?

![stuck2](https://user-images.githubusercontent.com/66367547/101988635-acfbb180-3c92-11eb-96e1-99855756cdd3.png)

![stuck 3](https://user-images.githubusercontent.com/66367547/101988745-930e9e80-3c93-11eb-8e15-79f2b41d42b2.png)
.

**Comment by chimp1984** [comment] 2020-12-13 01:24
> Well, deleting PendingTrades indeed worked as you said it would. I did the SPV re-sync and all seems to be ok. The transaction is completely gone now; there is no record of it, as if it had never happened. I am satisfied with the result, but I am not sure if the seller was able to recover their BTC.

As there was not deposit tx not funds got locked up. But he might have similar UI issues as you had. I guess he will reach out to support.

**Comment by chimp1984** [comment] 2020-12-13 01:27
I though the fix was already deployed but its not and will be in the next release: https://github.com/bisq-network/bisq/pull/4921

I think best is to wait for 1.5.2. then you will be able to move it to failed trades.
Just ignore that trade. The deposit tx was not created so no funds are locked up.

**Closed as completed** 2020-12-20 19:49 UTC
Labels: in:trade-process, in:wallet
