### ISSUE TITLE
Fix Bank transfer 'Copy BSB number' bug

### ISSUE THREAD

**Issue by Conza88** [bisq-network/bisq#5200] opened 2021-02-17 11:28 UTC
### Steps to reproduce
- Take offer
- National Bank Transfer method
- Go to pay trader, open trade ID details
- Hit copy the :BSB code: number
- *Instead it copies the BANK NAME, not the BSB code/number

Most certainly first world problems I know, but is a small fix hopefully.

May be present on OTHER bank payment methods as well. 

![image](https://user-images.githubusercontent.com/51952482/108187175-49927200-7162-11eb-8a71-7a5ddcf639d1.png)

**Comment by pazza83** [comment] 2021-02-17 11:35
Thanks for this I will take a look.

**Comment by BtcContributor** [comment] 2021-02-23 17:28
Not sure if I can reproduce that @Conza88, at least on 1.5.6.
If I click on the copy button I obtain the value of _Bank name / BSB code_ together and it seems good to me.

Maybe it has already been fixed?

**Comment by Conza88** [comment] 2021-02-23 19:15
Should it not just be the BSB number on its own?

You don't need the bank name when putting into transfer at all. The BSB and account number together look that up.

When I paste it currently into bsb box it pastes the stupid bank name instead and gets cut off

**Comment by BtcContributor** [comment] 2021-02-23 19:41
I think that the copy button means copy everything in the box and that's what is happening right now.
If just the second part of the box is needed instead, I can propose a fix for that.

**Comment by Conza88** [comment] 2021-02-23 19:48
That's exactly what I'm proposing.
________________________________

**Comment by BtcContributor** [comment] 2021-02-24 11:28
Fixed @Conza88.
It is trivial to add other similar scenarios, if needed.

**Comment by Conza88** [comment] 2021-02-24 18:20
Awesome. Yes, pretty simple.

Is there any reason any bank transfers need the other bank name?

**Comment by BtcContributor** [comment] 2021-02-24 18:34
Not sure about that.

**Comment by pazza83** [comment] 2021-02-28 02:25
> Is there any reason any bank transfers need the other bank name?

@Conza88, good question.  

I think it is standard practice when making payment to someone to know the bank you are transferring to. However really the info is not needed as you have the BIC / Sort Code / BSB Code etc.

That being said I do not think it really gives too much away as because you have the above you would be able to find their bank name anyway.

Let me know if you think it is / is not needed.

**Closed as completed** 2021-03-12 08:54 UTC
Labels: a:bug, in:gui, good first issue
