### ISSUE TITLE
Error: “BuyerVerifiesFinalDelayedPayoutTx

### ISSUE THREAD

**Issue by atom-mota** [bisq-network/bisq#4142] opened 2020-04-08 16:35 UTC
### Description

I just upgraded to Bisq 1.3.0 > I successfully created about 4 new BTC buy orders > a couple were taken > and this error appeared
Error: “BuyerVerifiesFinalDelayedPayoutTx 
see image and logs attached
<img width="1050" alt="Screen Shot 2020-04-08 at 1 20 00 PM" src="https://user-images.githubusercontent.com/61920767/78809310-178a7e00-799d-11ea-865c-34e3c010ae2f.png">

#### Version

Bisq 1.3.0
### Steps to reproduce

Unknown steps > I had upgraded to Bisq 1.3.0  successfully > I successfully created 4 new BTC Buy orders > a couple of these offers were taken > and at some point after the 2nd offer was taken by a trader, this error appeared

### Actual behaviour

I observed the issue mentioned above AND I also observed this other error alert appear Twice, a few minutes before getting the "BuyerVerifiesFinalDelayedPayoutTx " error.

<img width="839" alt="Screen Shot 2020-04-08 at 1 15 33 PM" src="https://user-images.githubusercontent.com/61920767/78809556-8071f600-799d-11ea-8aed-0b8f620d5705.png">
But I had already withdrawn all my funds prior to upgrading to 1.3.0 so I'm unsure what this is due to
#### Device or machine
Mac OS X 10.15.3 Catalina

#### Additional info
[Bisq-logs-issue.txt](https://github.com/bisq-network/bisq/files/4451655/Bisq-logs-issue.txt)

**Comment by mattmill30** [comment] 2020-04-08 17:26
I've also got this issue, I'll create a separate Bug report because the steps to reproduce are from filling a buy order

**Comment by mattmill30** [comment] 2020-04-08 18:18
Same fault from buyers perspective - #4145

**Comment by atom-mota** [comment] 2020-04-08 18:25
I just reproduced this again. Apparently, for every new Order I take, the issue appears. The order seems to start fine. i.e. I am getting confirmations and I am sending the fiat payments fine. 
I am attaching logs here too after this issue appeared 
<img width="1086" alt="Screen Shot 2020-04-08 at 3 01 57 PM" src="https://user-images.githubusercontent.com/61920767/78819830-398bfc80-79ad-11ea-92b0-becfa9a8425c.png">

[bisq-issue-2-taking buy offer.txt](https://github.com/bisq-network/bisq/files/4452162/bisq-issue-2-taking.buy.offer.txt)

Another thing I observe is that the "payment started message status" for ALL my trades says "Undefined ?" 
<img width="463" alt="Screen Shot 2020-04-08 at 3 33 28 PM" src="https://user-images.githubusercontent.com/61920767/78820560-65f44880-79ae-11ea-801f-df43dfb602d1.png">

**Comment by huey735** [comment] 2020-04-08 20:35
Hi. A new update is being worked on and should be released soon.

**Comment by huey735** [comment] 2020-04-08 21:00
These issues may have been fixed with the latest update v.1.3.1
https://github.com/bisq-network/bisq/releases/tag/v1.3.1

**Comment by mattmill30** [comment] 2020-04-09 17:04
I would still like support with this bug in the issue I linked above.

If this ticket isn't being actively resolved any longer, following the last post regarding upgrading to v1.3.1, perhaps it could be marked as a duplicate

**Closed as completed** 2020-07-18 05:30 UTC
Labels: was:dropped
