### ISSUE TITLE
App support keyboard shortcut does not work

### ISSUE THREAD

**Issue by pmknutsen** [bisq-network/bisq#2626] opened 2019-04-03 09:50 UTC
The Bisq FAQ states that ctrl+o ror cmd+o will open a new support tickets, e.g. for reporting bugs. This shortcut does not work per v0.9.7 (Linux, Ubuntu 18.04).

**Comment by ManfredKarrer** [comment] 2019-04-03 14:59
Have you selected the trade? Check if you have capslock set?

**Comment by ripcurlx** [comment] 2019-04-04 09:05
@pmknutsen I just tried it out locally and it still works for me. As @ManfredKarrer mentioned you have to have a trade selected to be able to open a dispute.

**Comment by ripcurlx** [comment] 2019-04-04 09:06
Closing as not reproducable. Please re-open if you still have problems opening a dispute from within your client.

**Closed as completed by ripcurlx** 2019-04-04 09:06 UTC

**Comment by pmknutsen** [comment] 2019-04-04 09:09
My misunderstanding. The FAQ on bisq.network states that "If the Bisq application recognizes that you’re having a software problem, it will display a “support ticket” button. Your arbitrator will forward your bug report to the developers, who will begin an investigation of the problem. You may be asked for the log file to assist in the process. If the button does not appear, you can open a support ticket by hitting cmd+o (or ctrl+o, depending on your system)."

which I interpreted to mean ctrl+o would work form anywhere within the app (e.g. for reporting bugs), not just when requesting support for trades.

I would just clarify the FAQ in this case, mentioning its for ongoing trades only.

**Comment by ripcurlx** [comment] 2019-04-04 09:12
> My misunderstanding. The FAQ on bisq.network states that "If the Bisq application recognizes that you’re having a software problem, it will display a “support ticket” button. Your arbitrator will forward your bug report to the developers, who will begin an investigation of the problem. You may be asked for the log file to assist in the process. If the button does not appear, you can open a support ticket by hitting cmd+o (or ctrl+o, depending on your system)."
> 
> which I interpreted to mean ctrl+o would work form anywhere within the app (e.g. for reporting bugs), not just when requesting support for trades.
> 
> I would just clarify the FAQ in this case, mentioning its for ongoing trades only.

Yes, this is a little bit misleading in the docs (ping @m52go). The button that is referenced is displayed within the trade view if you have a trade selected that e.g. has reached the max. trade limit.
