### ISSUE TITLE
Takers deposit transaction rejected for 'too-long-mempool-chain' causing issues

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#3705] opened 2019-11-27 20:52 UTC
### Description

If a taker attempts to take too many offers that have not been confirmed, the deposit transaction will be rejected by the Bitcoin network for 'too-long-mempool-chain'. The affected trade will then be moved into his failed trades tab but remains open for the maker without any indication of an error.

The maker then likely waits for the trade timer to run out, with any chat attempts to contact the taker going unanswered (since chat messages are not shown to them for failed trades). Then the maker finally opens a support ticket and the mediator is able to communicate with both Alice and Bob (it will show up under the takers support tickets).

When the mediator suggests a payout, only the maker sees the mediation result in her open trades. The taker doesn't since the trade is in Failed trades. The maker is able to accept the result, but nothing happens since the taker is unable to accept as well. At this point, the maker is unable to contact the mediator (since the support ticket was closed), and is unable to contact the taker.

If the maker then tries to reject the result, she will encounter an error indicating the deposit transaction is not confirmed and unable to open an arbitration dispute [3]. And after doing an SPV resync, encounters an error that the trade has no deposit transaction set and to move it to failed trades [4].

#### Version

release/v.1.2.4 (commit hash 548a217751b44abab8452cef609ebefb420835f0)

### Steps to reproduce

Using a regtest setup, perform the following steps without generating any blocks:
1. Alice makes about 15 offers to buy BTC
2. Bob tries to take all the offers to sell BTC

### Actual behaviour

When attempting to take the 13th offer, Bob will encounter a transaction rejection error [1] and [2], and the trade will move into his Failed Trades tab. Meanwhile, the trade will show in Alice's open trades without any indication that an error occurred on the takers side. And even after generating several blocks, remains waiting for blockchain confirmation (note, I did see on a few attempts to reproduce this issue that it did eventually get confirmed after several blocks).

Note, the multisig deposit appears in both wallets, but remains unconfirmed.

### Expected behaviour

At a minimum, after Bob encounters the transaction rejection error, Alice's trade should update and indicate an error was encountered. Perhaps it needs to move to Failed Trades as well. Though ideally we should prevent this type of rejected transaction in the first place and perhaps block creating/taking too many offers without confirmation.

Additionally, do we need to allow chat for failed trades and potentially view mediator result for failed trades?

### Screenshots

[1]
![image](https://user-images.githubusercontent.com/603793/69756475-7d254e80-110f-11ea-9b05-a881ff4b264d.png)

[2]
![image](https://user-images.githubusercontent.com/603793/69756481-80b8d580-110f-11ea-990c-7aa6d0685d3c.png)

[3] 
![image](https://user-images.githubusercontent.com/603793/69769241-db1a5c00-1138-11ea-8a19-89fe12c9fd9a.png)

[4]
![image](https://user-images.githubusercontent.com/603793/69769385-7b708080-1139-11ea-96fa-2cb7610ad45f.png)

#### Environment

- Windows 10
- Regtest environment with Bitcoin core v0.18.1

#### Additional information

In Bitcoin Core if a transaction in the mempool has 25 descendants, or it and all of its descendants are over 101,000 vbytes, any newly-received transaction that is also a descendant will be rejected. So once you have 25+ UTXOs in a long unspent chain of unconfirmed transactions, you will encounter this issue. And since each take offer has 2 transactions (taker/tx fee and multisig deposit), that is why the issue was encountered when attempting to take the 13th offer.

**Comment by devinbileck** [comment] 2019-11-28 01:47
This may be related to the wallet corruption issues encountered lately. If you spend an invalid UTXO then your wallet is corrupted and you can even spread the corruption to other users this way. I have not confirmed this though.

**Comment by wiz** [comment] 2019-11-28 03:25
@chimp1984 I think this issue is what initially caused our recent wallet corruption issues - a very big market maker on Bisq quickly created 5 ~ 10 trades each on 5 ~ 10 different markets, and bypassed the Bitcoin rule for 25 unconfirmed transactions chained to each other. Then the maker corrupted every taker's wallets when they got corrupted, and it kept spreading like a virus...

**Comment by devinbileck** [comment] 2019-11-28 07:52
Note, if we decide to limit the number of offers placed/taken without confirmation, should also limit the number of BTC/BSQ transactions without confirmation, since that can cause the same type of rejected transaction. In fact after sending too many BSQ transactions and restarting the client, I encountered the following error and was unable to launch the app:

![image](https://user-images.githubusercontent.com/603793/69786986-62cf8d00-1170-11ea-8498-9d772d2b3416.png)

```
Nov-27 23:50:34.262 [JavaFX Application Thread] ERROR b.core.btc.setup.WalletsSetup: Service failure from state: STARTING; failure={} java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:469)
	at org.bitcoinj.wallet.Wallet.setTransactionBroadcaster(Wallet.java:5072)
	at org.bitcoinj.core.PeerGroup.addWallet(PeerGroup.java:1309)
	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:455)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.base/java.lang.Thread.run(Thread.java:844)

java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:469)
	at org.bitcoinj.wallet.Wallet.setTransactionBroadcaster(Wallet.java:5072)
	at org.bitcoinj.core.PeerGroup.addWallet(PeerGroup.java:1309)
	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:455)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.base/java.lang.Thread.run(Thread.java:844)
Nov-27 23:50:34.266 [JavaFX Application Thread] ERROR bisq.core.app.WalletAppSetup: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING. 
```

**Comment by wiz** [comment] 2019-12-18 07:37
In case it's not clear, this is a high priority issue that causes user wallet corruption, that still reproduces in the current version of Bisq. A user reported their wallet was corrupted to me today after creating 25 offers within a short period of time.

**Comment by ripcurlx** [comment] 2019-12-18 10:48
> In case it's not clear, this is a high priority issue that causes user wallet corruption, that still reproduces in the current version of Bisq. A user reported their wallet was corrupted to me today after creating 25 offers within a short period of time.

I removed the milestone label not because I think it is not important, just plainly because no dev committed right now to implement it in-time for the v1.2.5 release. I do plan to have a look at it next, but I'm not sure how quickly it can be fixed in a proper way.

**Comment by wiz** [comment] 2019-12-19 16:15
Cool. Actually it's not as critical as it was before because the new "failed trades" feature is preventing it from spreading like a virus, but market makers who create a lot of offers quickly are still reporting their wallet getting corrupted. Of course I told them about the issue now that we know what's causing it, and they will create offers more slowly and wait for confirmations, but I just want to make sure this isn't forgotten 😅

**Comment by wiz** [comment] 2020-01-28 19:28
@ripcurlx this critical wallet corrupting bug has still not been addressed - could we target it for v1.2.6  ? I think all we need to do is handle the exception and prevent the user from making any more transactions after it passes a "soft limit" of 15 or so, I think the hard bitcoin limit is 25 unconfirmed transactions

**Comment by ripcurlx** [comment] 2020-01-29 10:56
> @ripcurlx this critical wallet corrupting bug has still not been addressed - could we target it for v1.2.6 ? I think all we need to do is handle the exception and prevent the user from making any more transactions after it passes a "soft limit" of 15 or so, I think the hard bitcoin limit is 25 unconfirmed transactions

Just a matter of resources and priority. I'll have a look how much dev time I've left for the v1.2.6 release after my current work.

**Comment by freimair** [comment] 2020-03-15 00:14
onto it

**Comment by wiz** [comment] 2020-03-17 12:13
Call discussion nodes with @freimair about how to tackle this:

1) fix mempool fee estimation https://github.com/bisq-network/projects/issues/27
2) mitigate causes of the too-long-mempool-chain issue from reproducing by implementing a "soft limit" and "hard limit" in many various places on both maker and taker sides
3) since we can't prevent all causes, we still need to handle the currently-unhandled exception state of when you get a broadcast fail error (due to too-long-mempool-chain error), because it could actually get confirmed later, and
4) we need to add a "refund" by doublespending funding TX back to a fresh unused address
5) this bug blocks the GRPC API from being possible because a trading bot creating many offers quickly would immediately trigger this bug and corrupt the wallet (cc @cbeams )
6) as an additional verification step, to check if a deposit TX is valid, since Bisq cannot know (due to limitations of SPV), we could possibly query a REST API backend running on a federated btcnode, if the TXID exists in that full node's mempool - if it does, then it's probably valid
7) the final answer (end of the flow chart) must either be that the deposit TX got confirmed, or a refund TX got confirmed (refund of funding TX)
8) don't need all of the above ideas implemented, can add one at a time, as they all help to mitigate the severity of the issue

**Comment by wiz** [comment] 2020-03-17 12:14
9) currently 8 ~ 10 cases per month of this issue, the goal should be to reduce it to less than 1 case per month

**Closed as completed** 2020-04-10 13:23 UTC
Labels: a:bug, is:priority, is:critical

**Comment by cbeams** [comment] 2020-08-21 08:29
@devinbileck wrote in https://github.com/bisq-network/bisq/issues/3705#issuecomment-559381012

> [...]
>
> ![image](https://user-images.githubusercontent.com/603793/69786986-62cf8d00-1170-11ea-8498-9d772d2b3416.png)
> 
> ```
> [...]
> 
> java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:469)
> 	at org.bitcoinj.wallet.Wallet.setTransactionBroadcaster(Wallet.java:5072)
> 	at org.bitcoinj.core.PeerGroup.addWallet(PeerGroup.java:1309)
> 	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:455)
> 	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
> 	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
> 	at java.base/java.lang.Thread.run(Thread.java:844)
> Nov-27 23:50:34.266 [JavaFX Application Thread] ERROR bisq.core.app.WalletAppSetup: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING. 
> ```

I just ran into this error and was able to get around it by shutting down Bisq, [deleting my SPV file from the filesystem](https://bisq.wiki/Resyncing_SPV_file#From_the_file_system) and restarting.

**Comment by eigentsmis** [comment] 2020-09-06 14:09
> @devinbileck wrote in [#3705 (comment)](https://github.com/bisq-network/bisq/issues/3705#issuecomment-559381012)
> 
> > [...]
> > ![image](https://user-images.githubusercontent.com/603793/69786986-62cf8d00-1170-11ea-8498-9d772d2b3416.png)
> > ```
> > [...]
> > 
> > java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.
> > 	at com.google.common.base.Preconditions.checkState(Preconditions.java:469)
> > 	at org.bitcoinj.wallet.Wallet.setTransactionBroadcaster(Wallet.java:5072)
> > 	at org.bitcoinj.core.PeerGroup.addWallet(PeerGroup.java:1309)
> > 	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:455)
> > 	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
> > 	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
> > 	at java.base/java.lang.Thread.run(Thread.java:844)
> > Nov-27 23:50:34.266 [JavaFX Application Thread] ERROR bisq.core.app.WalletAppSetup: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING. 
> > ```
> 
> I just ran into this error and was able to get around it by shutting down Bisq, [deleting my SPV file from the filesystem](https://bisq.wiki/Resyncing_SPV_file#From_the_file_system) and restarting.

Had the same issue recently and fixed it the same way as @cbeams

**Comment by coinzdude** [comment] 2020-09-26 16:17
I have this same error.  
![image](https://user-images.githubusercontent.com/58857646/94345168-02a8b200-fff2-11ea-88c4-159a301c7ad9.png)

If I manually delete the SPV file, will my offers still be valid?

---

I did delete the SPV file and I still see my offers in the market, so this looks good.
