### ISSUE TITLE
Candlesticks tooltips show inverted highs/lows for decimal BTC values

### ISSUE THREAD

**Issue by sam-sla** [bisq-network/bisq#2748] opened 2019-04-18 22:58 UTC
This example is for BSQ but I saw it was wrong for other coins as well. When the represented values are decimal BTC values, the highs and lows are switched
![image](https://user-images.githubusercontent.com/19795751/56396049-6d6e8f00-623d-11e9-8d4a-22eed662fd9c.png)

It looks correct if we look a fiat currency, presumably because the values are > 0
![image](https://user-images.githubusercontent.com/19795751/56396127-be7e8300-623d-11e9-850a-a8080f15b95b.png)

**Comment by freimair** [comment] 2019-07-14 08:56
duplicate of #2944. Please follow the progress over there.

**Closed as completed by freimair** 2019-07-14 08:56 UTC
Labels: in:gui
