### ISSUE TITLE
Java Heap Space

### ISSUE THREAD

**Issue by SusBra** [bisq-network/bisq#5610] opened 2021-07-08 05:51 UTC
### Description

Java Heap Space Bug

#### Version

v1.7.0
[bisq_java_heap_space_bug.txt](https://github.com/bisq-network/bisq/files/6781857/bisq_java_heap_space_bug.txt)

**Comment by ripcurlx** [comment] 2021-07-13 07:09
Duplicate of #5550.

**Closed as completed by ripcurlx** 2021-07-13 07:09 UTC
