### ISSUE TITLE
Are there any web service or web interface for bisq?

### ISSUE THREAD

**Issue by streetbits** [bisq-network/bisq#884] opened 2017-07-25 07:26 UTC

**Comment by cbeams** [comment] 2017-07-25 09:13
Hi @streetbits, looks like this is a duplicate of #544.

Note that the https://market.bisq.io webapp / API is out there, but it's providing read-only trading information, e.g. for use by https://cryptowat.ch and similar services.

**Closed as completed by cbeams** 2017-07-25 09:13 UTC

**Comment by streetbits** [comment] 2017-07-25 19:17
Thank you so much for pointing me out :+1:
