### ISSUE TITLE
spontaneous -5 error and java.lang.ArrayIndexOutOfBoundsException on Market screen

### ISSUE THREAD

**Issue by paultroon** [bisq-network/bisq#424] opened 2016-05-02 18:05 UTC
![image](https://cloud.githubusercontent.com/assets/1126871/14962800/e40b5eb4-10a0-11e6-818d-6553e5d4fadd.png)

Windows 10, x64 version 

java.lang.ArrayIndexOutOfBoundsException next time I went to that page.

**Comment by paultroon** [comment] 2016-05-02 18:10
last part of the error log:

May-02 16:14:25.315 [JavaFX Application Thread] WARN  i.b.p.p.k.KeepAliveManager: Connection with id 0a6027f3-e928-42af-ad4f-b3b109c30011 has not completed and is still in our map. We will try to ping that peer at the next schedule. 
May-02 16:14:48.323 [JavaFX Application Thread] WARN  i.b.p.p.k.KeepAliveManager: Connection with id 0a6027f3-e928-42af-ad4f-b3b109c30011 has not completed and is still in our map. We will try to ping that peer at the next schedule. 
May-02 19:08:55.939 [JavaFX Application Thread] WARN  i.b.p.p.BroadcastHandler: Connection stopped already 
May-02 19:49:53.126 [NioClientManager] WARN  o.b.n.ConnectionHandler: Error handling SelectionKey: An existing connection was forcibly closed by the remote host 
May-02 19:57:50.013 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-02 19:57:50.017 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= -5 
May-02 20:04:36.307 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-02 20:04:36.308 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= null 
May-02 20:04:36.346 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-02 20:04:36.349 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= -3 
May-02 20:08:20.856 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-02 20:08:20.856 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= null

**Comment by ivilata** [comment] 2016-05-03 06:20
Looks like a duplicate of #421. Do you get any strange behavior just before or after the error?

**Comment by ManfredKarrer** [comment] 2016-05-05 11:54
Fixed with https://github.com/bitsquare/bitsquare/commit/afb8c18d31825453e0070c0dc944867c42e627e7
Will be deployed with next version.

**Closed as completed by ManfredKarrer** 2016-05-05 11:54 UTC
