### ISSUE TITLE
A timeout occurred.

### ISSUE THREAD

**Issue by vitormilagres1992** [bisq-network/bisq#3602] opened 2019-11-12 22:07 UTC
I simply cannot complete any transactions. Right after I click on REVIEW TAKE OFFER TO BUY BITCOIN, I get the following message: A TIMEOUT OCCURRED, as you can see in the attached picture and in the log files.

I have tried to use it in two different locations (home and work), and I get the same error. On both instances I am running the same version 1.2.3 on Linux.

I have tried via Ethernet, wifi and even using my phone's hotspot. I have also tried it with two different sellers. Still the same error.

Thanks

![Screenshot from 2019-11-12 18-59-35](https://user-images.githubusercontent.com/44966647/68714769-4e3fa200-057f-11ea-8d85-b6c69bcfcd62.png)
[bisq.log](https://github.com/bisq-network/bisq/files/3838429/bisq.log)

**Comment by captainreptile** [comment] 2019-11-13 07:18
I experienced same error today while adding sell btc offer.  
After restarting the app i get a warning: 

> A transaction was rejected from the network for reason 'dust' (64).

as well as no connection to bitcoin network, offer fees were withdrawn and no offer or history in portfolio.

Using Linux and Bisq v1.2.3

**Comment by vitormilagres1992** [comment] 2019-11-14 11:59
This is so frustrating, it's happening to every single transaction I make. Yesterday I saw 7 different buy offers and I was willing to buy all of them, but guess what? None of them worked, not even a single one. What the hell is happening?

**Comment by captainreptile** [comment] 2019-11-14 14:16
I managed to solve it by forcing a resync: 

> Settings > NETWORK INFO

 and then hit on 

> "Delete SPV File and resync"

it took me ~45min to resync and since its working without any issue.

**Comment by vitormilagres1992** [comment] 2019-11-14 16:17
Tried it to resync it, but it didn't work. I've noticed I cannot do SAME BANK transactions, there's always this timeout error. The only ones that will go through are NATIONAL BANK and CASH DEPOSIT

**Comment by stejbac** [comment] 2019-11-22 22:07
I had a look through the attached logfile earlier. It appears that the issue is due to an inconsistency between the way `bisq.core.payment.ReceiptValidator` checks for a match between offer-taker bank account types (as used by the Offer Book & Take Offer views) and the validation later done in the constructor of `bisq.core.trade.Contract`. The latter is causing an error at the other end, as seen in the logfile:

> Nov-12 19:45:19.885 [JavaFX Application Thread] WARN  b.c.t.p.TradeProtocol: Received AckMessage with error state for InputsForDepositTxRequest from iocd6eflopmyvjkf.onion:9999 with tradeId 0c8skf-0656b80f-90b7-4a8b-9db5-aaef284cd632-123 and errorMessage=An error occurred at task: MakerCreateAndSignContract
Exception message: payment methods of maker and taker must be the same.
makerPaymentMethodId=SAME_BANK
takerPaymentMethodId=NATIONAL_BANK 

(It's not clear exactly why the taker is presented with a timeout error message, however.)

The validation done by `Contract` is stricter, as seen by the lines:

> `        String makerPaymentMethodId = makerPaymentAccountPayload.getPaymentMethodId();`
>`        String takerPaymentMethodId = takerPaymentAccountPayload.getPaymentMethodId();`
>`        // For SEPA offers we accept also SEPA_INSTANT takers`
>`        // Otherwise both ids need to be the same`
>`        boolean result = (makerPaymentMethodId.equals(PaymentMethod.SEPA_ID) && takerPaymentMethodId.equals(PaymentMethod.SEPA_INSTANT_ID)) ||`
>`                makerPaymentMethodId.equals(takerPaymentMethodId);`
>`        checkArgument(result, "payment methods of maker and taker must be the same.\n" +`
>`                "makerPaymentMethodId=" + makerPaymentMethodId + "\n" +`
>`                "takerPaymentMethodId=" + takerPaymentMethodId);`

The restriction that both payment method IDs are identical (except for SEPA offers) should possibly be relaxed to match the logic done in `ReceiptValidator`, which allows _SAME_BANK_ offers to be taken by _NATIONAL_BANK_ account holders when the country and bank IDs match.

**Comment by stejbac** [comment] 2019-11-22 23:43
I'm managed to reproduce the _SAME_BANK_ <-> _NATIONAL_BANK_ issue locally (on regtest). It looks like the timeout is due to flawed handling of the error response from the maker. On confirming to take the offer, it just sits there after the peer has already sent an error, until it actually times out.

**Comment by stejbac** [comment] 2019-11-23 23:40
I think the best solution for now is to change the code to simply disallow choosing a _Same Bank_ offer when the taker only has a _National Bank_ account (and otherwise exclude mismatched account types). A workaround, which should work right now for the taker, is to simply create an additional _Same Bank_ account with the same details, and make sure to select it upon choosing the offer. Unfortunately, it will need to be aged (& possibly signed) from scratch.

Slightly longer term, the rules for matching trade bank accounts of different types could possibly be relaxed (as suggested above), but that's complicated by the fact that the main error is happening on the peer's node, which could be out of date.

The issue of potentially misleading timeout errors was already known for a while, apparently, as there is a TODO to address it in `bisq.core.trade.protocol.BuyerAsTraderProtocol`. I think that could be addressed in a separate PR.

**Comment by ripcurlx** [comment] 2020-01-28 13:11
Closing as complete.

**Closed as completed by ripcurlx** 2020-01-28 13:11 UTC
