### ISSUE TITLE
Filter by currency box suddenly changes

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#610] opened 2016-09-25 04:21 UTC
Just looking at my screen with an NZD trade showing and the dropbox currency suddenly changed to NOK. Weird bug indeed. I took a snapshot but I was so surprised at this error I forgot to save it.

**Comment by ManfredKarrer** [comment] 2016-09-25 05:11
Yes I got that reported a few times, but could never reproduce it. Its on the bugfix list though....

**Comment by haiqu** [comment] 2016-09-25 09:58
Captured it this time:

![nok](https://cloud.githubusercontent.com/assets/13131219/18814565/6e9924b8-835a-11e6-9b42-7f210d0c0c7b.png)

**Comment by ripcurlx** [comment] 2018-01-30 10:59
If I see it correctly in OfferBookChartViewModel, the list of the available trade currencies is only updated on the creation of the View and everytime `inialize()` is called on the view which causes `activate()` to be called on the view model. If I understand it correctly this only changes when switching to other sections e.g.`Buy BTC`and not when switching between tabs (view is not re-initialized in this case). So we can rule out that this was caused by a change of the list itself. Looking through the rest of the code that causes a change of the selection there are just three places that could be the root of this problem:
https://github.com/bisq-network/exchange/blob/50c160712659a90079ad9563a4d333007035986e/gui/src/main/java/io/bisq/gui/main/market/offerbook/OfferBookChartView.java#L106-L109
This can't be the problem as it is tied to the list of currencies that isn't updated while staying on this view.
https://github.com/bisq-network/exchange/blob/50c160712659a90079ad9563a4d333007035986e/gui/src/main/java/io/bisq/gui/main/market/offerbook/OfferBookChartView.java#L161-L162
This is only called when the view is newly initialized which can also be ruled out in this case.
https://github.com/bisq-network/exchange/blob/50c160712659a90079ad9563a4d333007035986e/gui/src/main/java/io/bisq/gui/main/market/offerbook/OfferBookChartView.java#L164-L170
And if this action would be triggered it would cause an update also of the chart which in this screenshot stayed with NZD. So it's also not this part of the code, that could cause this problem. As I'm not able to re-produce theoretically this bug with the current code base I'll close it for now.

**Closed as completed by ripcurlx** 2018-01-30 10:59 UTC
Labels: a:bug, in:gui, was:dropped
