### ISSUE TITLE
Unsupported private_key algorithm

### ISSUE THREAD

**Issue by onlymarcus** [bisq-network/bisq#3304] opened 2019-09-21 20:27 UTC
The day I installed the bisq connected normally and I sent some btc to the wallet and made a sale offer. The next day started to give this problem, already rotated the internet from my mobile and still without connecting. On my work computer I have another wallet that works normally on fedora 30. On another windows xp computer i use bisq and it works normally. 
Here in my house is windows 10, Brazil.
I already uninstalled, deleted the backup and reinstalled, but nothing worked.

![bisqerror](https://user-images.githubusercontent.com/36059034/65378847-dea2ea00-dc94-11e9-84bd-f5d6b610774c.JPG)

"Connection to p2p network failed ( Bug reported: Unsupported private_key algorithm. Did Tor get a new key type for hidden services? Please check your internet connection or try restarting the program."
I installed the latest version of bisq.
I don't know where the error log is.

**Comment by freimair** [comment] 2019-09-27 13:01
there will be a more verbose error message at the next tor update.

windows 10 you say?

Here are some of the reasons we found to cause such an issue:
- antivirus locks/deletes tor files
- windows locks tor files

@HarryMacfinned can you share the info where one can find the logs?

**Comment by datography** [comment] 2019-11-16 11:23
Having same issue after exactly the same scenario (1 day no problems, sell btc, close client, next day having this error).

**Comment by chimp1984** [comment] 2019-11-16 14:30
Do you use Windows and AV software? If so use a better AV software or better change to Linux or OSX. Some AV software cause problems with Tor and/or the app.

**Comment by ripcurlx** [comment] 2020-01-28 14:32
@onlymarcus Is it stll not working for you? If yes, please re-open this issue.

**Comment by m52go** [comment] 2020-02-07 17:41
Just want to comment that I encountered this issue.

1. Start Bisq v1.2.5 (release build) with a new data directory.
2. Wait for it to finish fully starting up, sync blockchain, etc.
3. Close Bisq, and it exits gracefully.
4. Open it again after about 30 seconds.
5. Get the error. (`Feb-07 12:03:44.430 [NetworkNode-9999] ERROR b.n.p.n.TorNetworkNode: Could not connect to running Tor: Unsupported private_key algorithm. Did Tor get a new key type for hidden services?`)
6. Close gracefully.
7. Start again, fails with same error, so delete outdated Tor files and shut down gracefully.
8. Open again, fails again with same error.
9. Close gracefully.
10. Delete `hiddenservices` folder.
11. Open, and it starts fine.

Screenshot:

![Screenshot from 2020-02-07 12-05-00](https://user-images.githubusercontent.com/735155/74069297-ac9ce500-49f5-11ea-863f-c0f1835d06b1.png)

When I say it shuts down "gracefully" I mean it doesn't hang indefinitely with the "Shutting down application can take a few seconds" message, like it sometimes does, requiring me to kill it manually. I'm not on Windows.

I couldn't reproduce the issue (made a second new data directory, followed steps 1-4, and didn't encounter 5) but it's an issue that is still present in some form.

**Comment by datography** [comment] 2020-02-08 01:45
I confirm that this problem still persists.

**Comment by huey735** [comment] 2020-02-10 11:59
Out of fear of creating a duplicate issue I'll post this here, [from a thread on bisq.community](https://bisq.community/t/failed-to-decode-rsa-key/8961):


## "
When I close Bisq and attempt to restart it I’m presented with the following:

! Warning
Connecting to the Bisq network failed (reported error: Error reply: Failed to decode RSA key)

A good Samaritan on the IRC channel helped me figure out that if I delete the following directory I can get it to start again, but I’m hoping to find a permanent fix:

~/.local/share/Bisq/btc_mainnet/tor/hiddenservice

My Specs:
Platform: Pinebook Pro
OS: Manjaro (arm64)
Running Bisq inside a Debian Chroot because OpenJDK on Manjaro doesn’t support JavaFX.

Really looking forward to getting this working on this <$250 Linux laptop. Thanks in advance for your help.
## "

@ripcurlx @freimair

**Comment by freimair** [comment] 2020-02-11 10:35
thanks for the reports. I am currently sketching up a roadmap on how we can give the tor stack the love it needs.

**Comment by gfuce** [comment] 2020-03-27 13:26
For anybody getting "Failed to decode RSA key", this is caused when using an external Tor version >0.4.2.3-alpha. Newer Tor daemon versions automatically give a V3 private key (ED25519) when a hidden service is requested via the `ADD_ONION NEW:BEST` control protocol command (which Bisq uses on it's first run to generate a HS private key).

I was able to workaround this by manually generating a V2 (RSA1024) key with (replacing `$BISK_DATA_DIR` with your data dir location):

```console
ssh-keygen -t rsa -f $BISK_DATA_DIR/btc_mainnet/tor/hiddenservice/private_key -b 1024
```

**Comment by gfuce** [comment] 2020-03-27 13:29
And to anybody else who deleted their `hiddenservice` directory as recommended by some troubleshooting steps, you really shouldn't do this while you have an open trade :disappointed:

**Comment by cd2357** [comment] 2020-10-13 15:10
Closing, as the solution was clarified above by @gfuce

**Closed as completed by cd2357** 2020-10-13 15:10 UTC
Labels: re:Tor
