### ISSUE TITLE
Recover from seed

### ISSUE THREAD

**Issue by purpurato** [bisq-network/bisq#2702] opened 2019-04-11 22:15 UTC
I want to recover my wallet funds from seed, but got this message. 
[bisq.log](https://github.com/bisq-network/bisq/files/3070805/bisq.log)

**Comment by ManfredKarrer** [comment] 2019-04-12 01:45
Hm... weird exception I never saw before. In the BitcoinJ source code the CouldNotAdjustDownwards is thrown:
> if emptying the wallet was requested and the output can't be shrunk for fees without violating a protocol rule.

Do you have the original wallet still?

@oscarguindzberg Any idea how to help the user?

**Comment by oscarguindzberg** [comment] 2019-04-12 13:10
Looks like a duplicate of https://github.com/bisq-network/bisq/issues/2640

**Comment by oscarguindzberg** [comment] 2019-04-12 13:12
I will reply on the original https://github.com/bisq-network/bisq/issues/2640 issue

**Comment by ManfredKarrer** [comment] 2019-04-13 02:34
Close as duplicate from https://github.com/bisq-network/bisq/issues/2640

**Closed as completed by ManfredKarrer** 2019-04-13 02:34 UTC
Labels: in:wallet
