### ISSUE TITLE
Market Spread Buy/Sell BTC columns flipped?

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1231] opened 2018-01-18 17:37 UTC
It looks like the ***Selll/Buy BTC*** column values are flipped.  Eg. Siacoin it shows two ***Buy BTC*** orders:

![image](https://user-images.githubusercontent.com/1538617/35112613-dcb50252-fc7e-11e7-88ae-b8778075aed4.png)

While there are actually ...

***Sell BTC*** orders:
![image](https://user-images.githubusercontent.com/1538617/35112372-22cf1530-fc7e-11e7-9236-c6e654af4859.png)

***Buy BTC*** orders: 
![image](https://user-images.githubusercontent.com/1538617/35112336-06554aaa-fc7e-11e7-8630-2355c98fefaf.png)

**Comment by ripcurlx** [comment] 2018-01-19 10:21
Good catch! This seems to be a bug.

**Comment by ripcurlx** [comment] 2018-01-25 16:24
I just walked through the current behavior with @ManfredKarrer again. It is not a bug, it's just a mind bending task atm to see it correctly. In the **Sell BTC** tab the **Sell** means, you want to the sell BTC and buy SC. So these two users want to Buy BTC by selling SC. This is also the point of view presented in the spread table, where you find these two offers in the **Buy BTC** column. This is quite confusing which is true, why I'll start with the first mockup for a new trading process (see https://github.com/bisq-network/exchange/issues/1207) tomorrow. Still I'll close this issue, as it is not a bug.

**Closed as completed** 2018-01-25 16:25 UTC
Labels: in:gui, was:invalid

**Comment by tr37ion** [comment] 2018-01-25 19:10
Just an addition: Bisq should display lists and values from only one view - the user's view. Mixing two different views confuses the user IMHO. 

Please consider only showing lists the current Bisq user expects/is interested in. It is not important to see what `..these two users want ...buy/sell..". Therefore, please keep in mind fixing this with #1207.
