### ISSUE TITLE
Bisq doesn't connect to local node on same pc

### ISSUE THREAD

**Issue by montvid** [bisq-network/bisq#1154] opened 2018-01-05 12:14 UTC
I have bitcoin core 0.15.1 running on my pc. The node was not fully synced so bisq instead of connecting to it was connecting to 165.227.34.56:8333. Only when my node synced fully bisq connected to it.

I expected bisq would connect to my node 127.0.0.1:8333 or at least to a node via TOR but not 165.227.34.56. The "Bitcoin Network" tab was grayed out - I could not change any settings.

**Comment by ManfredKarrer** [comment] 2018-01-05 19:12
Have you checked your external IP? Maybe it was 165.227.34.56? Otherwise it would require some special handling for not-synced nodes to alert the user to decide what he wants to do in such a case.

**Comment by montvid** [comment] 2018-01-05 19:30
It is not. If you check the ip is Digital Ocean. And if you check bisq while running a btc node on the same pc bisq shows 127.0.0.1 as ip address of the node (correctly).

The problem is that bisq connects to some random node not using TOR (while thinking that it is connected to my pc's node) while by default it should use TOR if connecting to random nodes.

Preferred behavior: If bisq detects that my node is not synced it should connect to a node/nodes using TOR or wait until my local node finishes syncing and connects to 127.0.0.1.
Actual behavior:  bisq detects that my node 127.0.0.1 is not synced it connects to a node 165.227.34.56.

**Comment by ManfredKarrer** [comment] 2018-01-19 20:00
I can confirm now that there is an issue that when Bitcoin Core is syncing the connection from Bisq fails and then Bisq use a public clearnet node instead leading not only to unexpected exposure of privacy (bloomfilter) but also to risks that a tx broadcast will not succeed because only 1 node is not very reliable for broadcast. BitcoinJ treats that case as normal connection to the public network with the defined nr. of peers (9) but in reality there will be only 1 node thus the broadcast does never start as BitcoinJ waits for 4 peers. That triggers a timeout where we broadcast to all our connected nodes (only 1 in that case) and assume that the broadcast eventually succeed. 

We need to detect if the connection to LocalHost fails and if that is the case show a popup telling the user that the local node is not yet ready. We should then retry to connect after a certain delay until we get successfully connected. Fallback to public clearnet nodes must be avoided.

**Comment by ManfredKarrer** [comment] 2018-01-21 00:57
That issue is now fixed in master branch (will be released soon to 0.6.4)

**Closed as completed by ManfredKarrer** 2018-01-21 00:57 UTC
