### ISSUE TITLE
Locked up funds from a failed trade

### ISSUE THREAD

**Issue by dwknch** [bisq-network/bisq#2925] opened 2019-06-27 11:24 UTC
See also issue #2924 reported just minutes ago.

This issue came with to pop-ups.

First pop-up is a warning about locked-up funds from a failed trade
![Warning-locked-up-funds](https://user-images.githubusercontent.com/52279677/60262466-7e431d00-98de-11e9-8d67-a774feae6475.png)

Second pop-up is an error with java.lang.IllegalArgumentException. This one asks me to file an issue.
![Error-illegal-argument](https://user-images.githubusercontent.com/52279677/60262558-b3e80600-98de-11e9-9f8b-5f2e78328a47.png)

Finally I'm sending you the corresponding log file
[bisq.log](https://github.com/bisq-network/bisq/files/3334369/bisq.log)

Thanks

**Comment by dwknch** [comment] 2019-06-27 12:48
An additional problem that currently hinders proper use of the Bisq client on my side:
Every time I try to switch to the "open trades" tab under "portfolio" tab, I get the Error with java.lang.IllegalArgumentException (see other screenshot) and after closing the error screen it remains empty as in the following screenshot:
![empty-open-trades](https://user-images.githubusercontent.com/52279677/60267277-2ca08f80-98ea-11e9-96df-39d820b77c28.png)

The little "2" on the portfolio tab seems to suggest that there are 2 open trades. 
However none of "my open orders" has disappeared, which usually would happen after successful creation of a trade.

Anyone facing the same issue? How to get the situation unstuck? 
Reinitialize the app with the seed phrase? Any suggestion welcome.

**Comment by sqrrm** [comment] 2019-06-27 13:33
Looking at the log file it's throwing the IllegalArgumentException due to the price of a trade being non positive. This is probably the failed trade so the problem will persist.

I can't think of a good way to handle this right now. Will have to come back on that.

**Comment by dwknch** [comment] 2019-06-27 15:23
Hello and thank you for looking into this for me.

In the meantime the BTC buyer paid me in EUR on Revolut (that was while my
client was offline, so I think it must be about the trade initiated when I
first saw the error, not a new trade)

Unfortunately, as the open trade list triggers the
IllegalArgumentException, I have no way to acknowledge the trade. Any idea
how I might resolve my situation? Hacking into some files in the data
folder?

I'm also not able to open a support issue in Bisq, because this is usually
done starting from an open trade if I understood that right.

Edit: quoted message removed

**Comment by sqrrm** [comment] 2019-06-27 15:42
If you're feeling adventurous you can try building from my PR at https://github.com/bisq-network/bisq/pull/2926. I haven't been able to test it since I couldn't reproduce your issue though, so it's completely untested. I don't think it could cause any harm though and it should avoid the IllegalArgumentException. You could also wait a bit to get some feedback from the other devs on this PR.

**Comment by dwknch** [comment] 2019-06-27 16:24
Thanks for the effort, but I don't feel that adventurous and don't have the time on my hands right now learning to build Bisq myself.
Good idea to wait and see what other devs might say.
Other question: since I'm not able to act from the pending trade tab, how will I be involved in the dispute that will inevitable come up in about 24 hours?

**Comment by sqrrm** [comment] 2019-06-27 16:49
The dispute resolution should be ok as long as you don't open the details of the contract. Your trade history won't show after that but we should have a fix for this soon enough.

**Comment by a123b** [comment] 2019-06-27 23:18
I think this is actually a duplicate of #2235, which was closed without being fixed for whatever reason...

**Comment by geg780** [comment] 2019-06-28 15:42
seems that the bisq client on the other side of the trade froze also when taking the trade.

**Comment by a123b** [comment] 2019-06-28 15:46
How do you know? I'd expect that the trade would fail with a timeout on the other side of the trade.

**Comment by geg780** [comment] 2019-06-28 15:52
cause im the buyer and i managed to contact the seller with the revolut phone number associated to the trade. my bisq client froze, i had to reboot and the trade showed up.

**Comment by a123b** [comment] 2019-06-28 16:01
Oh, I confused this issue with OP's other issue. If you are were having issues on the other side of this exact trade, it could be helpful if you upload your bisq.log file, too!

**Comment by UnityJon** [comment] 2019-06-29 01:17
Had same issue as OP.  returned to computer to get a bunch of popups.  1st one saying an attempt to take my offer was rejected because of price mismatch.  Then one that buyer had initiated payment.  Then one about funds locked up due to a failed trade.  After which couldn't go to open offers or it would crash with the java error.  Other party opened a dispute - and after arbitrator closed released all funds (I'd received payment and confirmed so) the error vanished and could trade again.  Was unable to confirm the trade or initiate a dispute myself.

**Comment by a123b** [comment] 2019-06-29 09:59
@UnityJon Interesting. Can you see the problematic trade in the portfolio history tab? And if you can, is the listed price for the trade correct?

**Comment by UnityJon** [comment] 2019-07-01 00:23
No, cant see the problematic trade - as now I get the java Nullpointer exception if I go to the history tab.

However, I do remember clearly that the mismatch error was that the seller offered to buy at about £9650/BTC when I was asking for £98xx.  The arbitrator who handled the dispute told me the price in the successful trade which was 9789.617 - that matched the sort of rate I was expecting and the amount of BTC I was selling plus amount of fiat received (£1214).

**Closed as completed** 2019-10-06 00:28 UTC
Labels: was:dropped
