### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by ciscoy2g17** [bisq-network/bisq#1310] opened 2018-02-01 03:29 UTC
Just upgraded from 0.6.2 to 0.6.4 ... Upon startup, after unlocking Bisq with my private key, I received an error and a prompt to post this to Github (scroll to Jan-31 22:12:11.507 for dump):

Jan-31 22:11:20.821 [JavaFX-Launcher] INFO  i.b.g.a.BisqApp: Log files under: /home/cisco/.local/share/Bisq/bisq 
Jan-31 22:11:20.858 [JavaFX-Launcher] INFO  i.b.c.u.Utilities: System info: os.name=Linux; os.version=4.4.0-112-generic; os.arch=amd64; sun.arch.data.model=64; JRE=1.8.0_131-b11 (Oracle Corporation); JVM=25.131-b11 (Java HotSpot(TM) 64-Bit Server VM) 
Jan-31 22:11:25.552 [JavaFX Application Thread] INFO  i.b.c.n.CoreSeedNodesRepository: seedNodeAddresses=[723ljisnynbtdohi.onion:8000, fl3mmribyxgrv63c.onion:8000, s67qglwhkgkyvr74.onion:8000, 3f3cu2yw7u457ztq.onion:8000, rm7b56wbrcczpjvl.onion:8000, jhgcy2won7xnslrb.onion:8000, 5quyxpxheyvzmb2d.onion:8000, ef5qnzx6znifo3df.onion:8000] 
Jan-31 22:11:25.658 [JavaFX Application Thread] INFO  i.b.c.p.ProvidersRepository: selected baseUrl=http://rb2l2qale2pqzjyo.onion/, providerList=[http://xc3nh4juf2hshy7e.onion/, http://ceaanhbvluug4we6.onion/, http://44mgyoe2b6oqiytt.onion/, http://5bmpx76qllutpcyp.onion/, http://rb2l2qale2pqzjyo.onion/] 
Jan-31 22:11:27.179 [JavaFX Application Thread] INFO  i.b.c.a.Version: Version{VERSION=0.6.4, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=1, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
Jan-31 22:11:32.467 [checkIfLocalHostNodeIsRunningThread] INFO  i.b.g.m.MainViewModel: Localhost peer not detected. 
Jan-31 22:11:33.558 [readFromResourcesThread] INFO  i.b.n.p.s.P2PDataStorage: persistableNetworkPayloadMap size=16945 
Jan-31 22:11:33.559 [readFromResourcesThread] INFO  i.b.c.a.SetupUtils: readPersistableNetworkPayloadMapFromResources took 973 ms 
Jan-31 22:11:34.184 [JavaFX Application Thread] INFO  i.b.g.m.MainViewModel: startBasicServices 
Jan-31 22:11:34.187 [JavaFX Application Thread] INFO  i.b.g.m.MainViewModel: initP2PNetwork 
Jan-31 22:11:34.284 [NetworkNode-9999] INFO  i.b.n.p.n.TorNetworkNode: Starting tor 
Jan-31 22:11:52.260 [NetworkNode-9999] INFO  i.b.n.p.n.TorNetworkNode: 
################################################################
Tor started after 17977 ms. Start publishing hidden service.
################################################################ 
Jan-31 22:11:52.280 [JavaFX Application Thread] INFO  i.b.g.m.MainViewModel: initWalletService 
Jan-31 22:11:52.360 [NetworkNode-9999] INFO  i.b.n.p.n.TorNetworkNode: It will take some time for the HS to be reachable (~40 seconds). You will be notified about this 
Jan-31 22:11:52.398 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: Socks5Proxy for bitcoinj: socks5Proxy=localhost:38070	Version 5 
Jan-31 22:11:52.464 [JavaFX Application Thread] INFO  o.b.c.Context: Creating bitcoinj 0.14.4 context. 
Jan-31 22:11:52.484 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: We add a onion node. btcNode=onionAddress='r3dsojfhwcm7x7p6.onion', hostName='btc1.0-2-1.net', address='159.89.16.222', port='8333', operator='@manfredkarrer 
Jan-31 22:11:52.501 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: We add a onion node. btcNode=onionAddress='vlf5i3grro3wux24.onion', hostName='btc2.0-2-1.net', address='165.227.34.56', port='8333', operator='@manfredkarrer 
Jan-31 22:11:52.503 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: We add a onion node. btcNode=onionAddress='i3a5xtzfm4xwtybd.onion', hostName='btc3.0-2-1.net', address='165.227.44.202', port='8333', operator='@manfredkarrer 
Jan-31 22:11:52.509 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: We add a onion node. btcNode=onionAddress='fz6nsij6jiyuwlsc.onion', hostName='kirsche.emzy.de', address='78.47.61.83', port='8333', operator='@emzy 
Jan-31 22:11:52.510 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: We add a onion node. btcNode=onionAddress='c6ac4jdfyeiakex2.onion', hostName='node2.emzy.de', address='62.75.210.81', port='8333', operator='@emzy 
Jan-31 22:11:52.511 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: We add a onion node. btcNode=onionAddress='sjyzmwwu6diiit3r.onion', hostName='node1.emzy.de', address='163.172.171.119', port='8333', operator='@emzy 
Jan-31 22:11:52.512 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: We add a onion node. btcNode=onionAddress='poyvpdt762gllauu.onion', hostName='null', address='null', port='8333', operator='@emzy 
Jan-31 22:11:52.513 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: We add a onion node. btcNode=onionAddress='lgkvbvro67jomosw.onion', hostName='bitcoin.christophatteneder.com', address='174.138.35.229', port='8333', operator='@Christoph 
Jan-31 22:11:52.514 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: We add a onion node. btcNode=onionAddress='4jyh6llqj264oggs.onion', hostName='btc.vante.me', address='138.68.117.247', port='8333', operator='@miker 
Jan-31 22:11:52.515 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: We add a onion node. btcNode=onionAddress='mxdtrjhe2yfsx3pg.onion', hostName='btc2.vante.me', address='67.207.75.7', port='8333', operator='@miker 
Jan-31 22:11:52.516 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: We add a onion node. btcNode=onionAddress='3r44ddzjitznyahw.onion', hostName='btc4.0-2-1.net', address='185.25.48.184', port='8333', operator='@sqrrm 
Jan-31 22:11:52.518 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: We add a onion node. btcNode=onionAddress='z33nukt7ngik3cpe.onion', hostName='bcwat.ch', address='5.189.166.193', port='8333', operator='@sgeisler 
Jan-31 22:11:52.519 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: We add a onion node. btcNode=onionAddress='sslnjjhnmwllysv4.onion', hostName='btc.jochen-hoenicke.de', address='88.198.39.205', port='8333', operator='@jhoenicke 
Jan-31 22:11:52.520 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletsSetup: You connect with peerAddresses: [[r3dsojfhwcm7x7p6.onion]:8333, [vlf5i3grro3wux24.onion]:8333, [i3a5xtzfm4xwtybd.onion]:8333, [fz6nsij6jiyuwlsc.onion]:8333, [c6ac4jdfyeiakex2.onion]:8333, [sjyzmwwu6diiit3r.onion]:8333, [poyvpdt762gllauu.onion]:8333, [lgkvbvro67jomosw.onion]:8333, [4jyh6llqj264oggs.onion]:8333, [mxdtrjhe2yfsx3pg.onion]:8333, [3r44ddzjitznyahw.onion]:8333, [z33nukt7ngik3cpe.onion]:8333, [sslnjjhnmwllysv4.onion]:8333] 
Jan-31 22:11:52.610 [ STARTING] INFO  i.b.c.b.w.WalletConfig: Wallet directory: /home/cisco/.local/share/Bisq/btc_mainnet/wallet 
Jan-31 22:11:52.707 [JavaFX Application Thread] INFO  i.b.n.p.p.g.RequestDataHandler: We send a PreliminaryGetDataRequest to peer 5quyxpxheyvzmb2d.onion:8000.  
Jan-31 22:11:52.786 [JavaFX Application Thread] INFO  i.b.n.p.p.g.RequestDataHandler: We send a PreliminaryGetDataRequest to peer 3f3cu2yw7u457ztq.onion:8000.  
Jan-31 22:11:53.986 [ STARTING] INFO  o.b.c.AbstractBlockChain: chain head is at height 507037:
 block: 
   hash: 00000000000000000030baf76244d629db15be22aae6d25961a57c8ad1cd2a3b
   version: 536870912 (BIP34, BIP66, BIP65)
   previous block: 000000000000000000223e61003b2278e42a24b22162282cdfd9267d7e109a4f
   merkle root: 6556b11a372b49f9bba796849aed279ea5574f2fe8d1a102feedebac5255fe1f
   time: 1517454109 (2018-02-01T03:01:49Z)
   difficulty target (nBits): 392962374
   nonce: 2508199795
 
Jan-31 22:11:54.577 [ STARTING] INFO  i.b.c.b.w.WalletConfig: We try to connect to 9 btc nodes 
Jan-31 22:11:54.729 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Starting ... 
Jan-31 22:11:54.767 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Localhost peer not detected. 
Jan-31 22:11:55.156 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [r3dsojfhwcm7x7p6.onion]:8333     (0 connected, 1 pending, 9 max) 
Jan-31 22:11:55.226 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [sslnjjhnmwllysv4.onion]:8333     (0 connected, 2 pending, 9 max) 
Jan-31 22:11:55.255 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [z33nukt7ngik3cpe.onion]:8333     (0 connected, 3 pending, 9 max) 
Jan-31 22:11:55.266 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [3r44ddzjitznyahw.onion]:8333     (0 connected, 4 pending, 9 max) 
Jan-31 22:11:55.286 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [mxdtrjhe2yfsx3pg.onion]:8333     (0 connected, 5 pending, 9 max) 
Jan-31 22:11:55.288 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [4jyh6llqj264oggs.onion]:8333     (0 connected, 6 pending, 9 max) 
Jan-31 22:11:55.298 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [lgkvbvro67jomosw.onion]:8333     (0 connected, 7 pending, 9 max) 
Jan-31 22:11:55.302 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [poyvpdt762gllauu.onion]:8333     (0 connected, 8 pending, 9 max) 
Jan-31 22:11:55.304 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [sjyzmwwu6diiit3r.onion]:8333     (0 connected, 9 pending, 9 max) 
Jan-31 22:12:04.674 [BlockingClient network thread for sjyzmwwu6diiit3r.onion:8333] INFO  o.b.core.Peer: Announcing to sjyzmwwu6diiit3r.onion:8333 as: /bitcoinj:0.14.4/Bisq:0.6.4/ 
Jan-31 22:12:05.008 [BlockingClient network thread for r3dsojfhwcm7x7p6.onion:8333] INFO  o.b.core.Peer: Announcing to r3dsojfhwcm7x7p6.onion:8333 as: /bitcoinj:0.14.4/Bisq:0.6.4/ 
Jan-31 22:12:05.712 [ScryptUtil:deriveKeyWithScrypt-0] INFO  o.b.c.KeyCrypterScrypt: Deriving key took 2.017 s for 32768 scrypt iterations. 
Jan-31 22:12:05.829 [BlockingClient network thread for z33nukt7ngik3cpe.onion:8333] INFO  o.b.core.Peer: Announcing to z33nukt7ngik3cpe.onion:8333 as: /bitcoinj:0.14.4/Bisq:0.6.4/ 
Jan-31 22:12:06.393 [BlockingClient network thread for z33nukt7ngik3cpe.onion:8333] INFO  o.b.core.Peer: [z33nukt7ngik3cpe.onion]:8333: Got version=70015, subVer='/Satoshi:0.15.0.1/', services=0x13, time=2018-01-31 22:11:44, blocks=507037 
Jan-31 22:12:06.395 [BlockingClient network thread for r3dsojfhwcm7x7p6.onion:8333] INFO  o.b.core.Peer: [r3dsojfhwcm7x7p6.onion]:8333: Got version=70015, subVer='/Satoshi:0.15.1/', services=0x13, time=2018-01-31 22:12:04, blocks=507037 
Jan-31 22:12:06.405 [BlockingClient network thread for r3dsojfhwcm7x7p6.onion:8333] INFO  o.b.c.PeerGroup: [r3dsojfhwcm7x7p6.onion]:8333: New peer      (1 connected, 8 pending, 9 max) 
Jan-31 22:12:06.450 [BlockingClient network thread for sjyzmwwu6diiit3r.onion:8333] INFO  o.b.core.Peer: [sjyzmwwu6diiit3r.onion]:8333: Got version=70015, subVer='/Satoshi:0.15.1/', services=0x13, time=2018-01-31 22:12:04, blocks=507037 
Jan-31 22:12:06.469 [BlockingClient network thread for r3dsojfhwcm7x7p6.onion:8333] INFO  o.b.c.PeerGroup: Setting download peer: [r3dsojfhwcm7x7p6.onion]:8333 
Jan-31 22:12:06.497 [BlockingClient network thread for z33nukt7ngik3cpe.onion:8333] INFO  o.b.c.PeerGroup: [z33nukt7ngik3cpe.onion]:8333: New peer      (2 connected, 7 pending, 9 max) 
Jan-31 22:12:06.499 [BlockingClient network thread for sjyzmwwu6diiit3r.onion:8333] INFO  o.b.c.PeerGroup: [sjyzmwwu6diiit3r.onion]:8333: New peer      (3 connected, 6 pending, 9 max) 
Jan-31 22:12:06.649 [BlockingClient network thread for r3dsojfhwcm7x7p6.onion:8333] INFO  o.b.core.Peer: Received alert from peer [r3dsojfhwcm7x7p6.onion]:8333: URGENT: Alert key compromised, upgrade required 
Jan-31 22:12:06.661 [BlockingClient network thread for sjyzmwwu6diiit3r.onion:8333] INFO  o.b.core.Peer: Received alert from peer [sjyzmwwu6diiit3r.onion]:8333: URGENT: Alert key compromised, upgrade required 
Jan-31 22:12:06.680 [BlockingClient network thread for z33nukt7ngik3cpe.onion:8333] INFO  o.b.core.Peer: Received alert from peer [z33nukt7ngik3cpe.onion]:8333: URGENT: Alert key compromised, upgrade required 
Jan-31 22:12:08.032 [JavaFX Application Thread] INFO  i.b.n.p.p.PeerManager: We have 2 connections open. Our limit is 12 
Jan-31 22:12:09.449 [BlockingClient network thread for sslnjjhnmwllysv4.onion:8333] INFO  o.b.core.Peer: Announcing to sslnjjhnmwllysv4.onion:8333 as: /bitcoinj:0.14.4/Bisq:0.6.4/ 
Jan-31 22:12:09.561 [BlockingClient network thread for lgkvbvro67jomosw.onion:8333] INFO  o.b.core.Peer: Announcing to lgkvbvro67jomosw.onion:8333 as: /bitcoinj:0.14.4/Bisq:0.6.4/ 
Jan-31 22:12:09.872 [BlockingClient network thread for lgkvbvro67jomosw.onion:8333] INFO  o.b.c.PeerGroup: [lgkvbvro67jomosw.onion]:8333: Peer died      (3 connected, 5 pending, 9 max) 
Jan-31 22:12:09.873 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Waiting 999 msec before next connect attempt to [c6ac4jdfyeiakex2.onion]:8333 
Jan-31 22:12:10.668 [BlockingClient network thread for mxdtrjhe2yfsx3pg.onion:8333] INFO  o.b.core.Peer: Announcing to mxdtrjhe2yfsx3pg.onion:8333 as: /bitcoinj:0.14.4/Bisq:0.6.4/ 
Jan-31 22:12:10.878 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [vlf5i3grro3wux24.onion]:8333     (3 connected, 6 pending, 9 max) 
Jan-31 22:12:11.015 [BlockingClient network thread for sslnjjhnmwllysv4.onion:8333] INFO  o.b.core.Peer: [sslnjjhnmwllysv4.onion]:8333: Got version=70015, subVer='/Satoshi:0.15.1/', services=0x13, time=2018-01-31 22:12:10, blocks=507037 
Jan-31 22:12:11.037 [BlockingClient network thread for sslnjjhnmwllysv4.onion:8333] INFO  o.b.c.PeerGroup: [sslnjjhnmwllysv4.onion]:8333: New peer      (4 connected, 5 pending, 9 max) 
Jan-31 22:12:11.041 [BlockingClient network thread for sslnjjhnmwllysv4.onion:8333] INFO  o.b.core.Peer: Received alert from peer [sslnjjhnmwllysv4.onion]:8333: URGENT: Alert key compromised, upgrade required 
Jan-31 22:12:11.212 [BlockingClient network thread for 3r44ddzjitznyahw.onion:8333] INFO  o.b.core.Peer: Announcing to 3r44ddzjitznyahw.onion:8333 as: /bitcoinj:0.14.4/Bisq:0.6.4/ 
Jan-31 22:12:11.505 [PriceRequest-HttpClientProvider{
     httpClient=HttpClient{socks5ProxyProvider=io.bisq.network.Socks5ProxyProvider@7edb677f, baseUrl='http://rb2l2qale2pqzjyo.onion/', ignoreSocks5Proxy=false}
}] ERROR i.b.c.p.p.PriceFeedService: Could not load marketPrices. Error: java.io.IOException: Error at requestWithGETProxy with URL: http://rb2l2qale2pqzjyo.onion/getAllMarketPrices. Throwable=SOCKS: Connection refused 
**Jan-31 22:12:11.507 [JavaFX Application Thread] WARN  i.b.c.p.p.PriceFeedService: request from priceProvider failed: errorMessage=Could not load marketPrices 
Jan-31 22:12:11.508 [JavaFX Application Thread] INFO  i.b.c.p.ProvidersRepository: Use new provider baseUrl: http://ceaanhbvluug4we6.onion/ 
Jan-31 22:12:11.509 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: Uncaught Exception from thread JavaFX Application Thread 
Jan-31 22:12:11.509 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: throwableMessage= null 
Jan-31 22:12:11.509 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: throwableClass= class java.lang.NullPointerException 
Jan-31 22:12:11.598 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: Stack trace:
java.lang.NullPointerException
	at io.bisq.core.provider.price.PriceFeedService.lambda$request$3(PriceFeedService.java:138)
	at io.bisq.core.provider.price.PriceFeedService$1.lambda$onFailure$2(PriceFeedService.java:320)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)**
 
Jan-31 22:12:11.732 [BlockingClient network thread for mxdtrjhe2yfsx3pg.onion:8333] INFO  o.b.core.Peer: [mxdtrjhe2yfsx3pg.onion]:8333: Got version=70015, subVer='/Satoshi:0.15.0.1/', services=0x13, time=2018-01-31 22:12:08, blocks=507037 
Jan-31 22:12:11.743 [BlockingClient network thread for mxdtrjhe2yfsx3pg.onion:8333] INFO  o.b.c.PeerGroup: [mxdtrjhe2yfsx3pg.onion]:8333: New peer      (5 connected, 4 pending, 9 max) 
Jan-31 22:12:11.859 [BlockingClient network thread for mxdtrjhe2yfsx3pg.onion:8333] INFO  o.b.core.Peer: Received alert from peer [mxdtrjhe2yfsx3pg.onion]:8333: URGENT: Alert key compromised, upgrade required 
Jan-31 22:12:11.999 [BlockingClient network thread for 3r44ddzjitznyahw.onion:8333] INFO  o.b.core.Peer: [3r44ddzjitznyahw.onion]:8333: Got version=70015, subVer='/Satoshi:0.15.1/', services=0x13, time=2018-01-31 22:12:11, blocks=507037 
Jan-31 22:12:12.038 [BlockingClient network thread for 3r44ddzjitznyahw.onion:8333] INFO  o.b.c.PeerGroup: [3r44ddzjitznyahw.onion]:8333: New peer      (6 connected, 3 pending, 9 max) 
Jan-31 22:12:12.170 [BlockingClient network thread for 3r44ddzjitznyahw.onion:8333] INFO  o.b.core.Peer: Received alert from peer [3r44ddzjitznyahw.onion]:8333: URGENT: Alert key compromised, upgrade required 
Jan-31 22:12:14.076 [JavaFX Application Thread] INFO  i.b.n.p.p.g.RequestDataHandler: 
#################################################################
Connected to node: 5quyxpxheyvzmb2d.onion:8000
Received 156 instances
MailboxStoragePayload: 75
Alert: 1
Arbitrator: 2
OfferPayload: 78
################################################################# 
Jan-31 22:12:14.433 [BlockingClient network thread for mxdtrjhe2yfsx3pg.onion:8333] INFO  o.b.c.PeerGroup: [mxdtrjhe2yfsx3pg.onion]:8333: Peer died      (5 connected, 3 pending, 9 max) 
Jan-31 22:12:14.453 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Waiting 981 msec before next connect attempt to [c6ac4jdfyeiakex2.onion]:8333 
Jan-31 22:12:15.412 [JavaFX Application Thread] INFO  i.b.g.m.MainViewModel: onBasicServicesInitialized 
Jan-31 22:12:15.438 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [fz6nsij6jiyuwlsc.onion]:8333     (5 connected, 4 pending, 9 max) 
Jan-31 22:12:19.937 [BlockingClient network thread for 4jyh6llqj264oggs.onion:8333] INFO  o.b.core.Peer: Announcing to 4jyh6llqj264oggs.onion:8333 as: /bitcoinj:0.14.4/Bisq:0.6.4/ 
Jan-31 22:12:20.006 [BlockingClient network thread for 3r44ddzjitznyahw.onion:8333] INFO  o.b.c.PeerGroup: [3r44ddzjitznyahw.onion]:8333: Peer died      (4 connected, 4 pending, 9 max) 
Jan-31 22:12:20.008 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Waiting 1499 msec before next connect attempt to [c6ac4jdfyeiakex2.onion]:8333 
Jan-31 22:12:21.286 [BlockingClient network thread for 4jyh6llqj264oggs.onion:8333] INFO  o.b.core.Peer: [4jyh6llqj264oggs.onion]:8333: Got version=70015, subVer='/Satoshi:0.15.0.1/', services=0x13, time=2018-01-31 22:12:17, blocks=507037 
Jan-31 22:12:21.449 [BlockingClient network thread for 4jyh6llqj264oggs.onion:8333] INFO  o.b.c.PeerGroup: [4jyh6llqj264oggs.onion]:8333: New peer      (5 connected, 3 pending, 9 max) 
Jan-31 22:12:21.455 [BlockingClient network thread for 4jyh6llqj264oggs.onion:8333] INFO  o.b.core.Peer: Received alert from peer [4jyh6llqj264oggs.onion]:8333: URGENT: Alert key compromised, upgrade required 
Jan-31 22:12:21.508 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [i3a5xtzfm4xwtybd.onion]:8333     (5 connected, 4 pending, 9 max) 
Jan-31 22:12:21.802 [BlockingClient network thread for 4jyh6llqj264oggs.onion:8333] INFO  o.b.c.PeerGroup: [4jyh6llqj264oggs.onion]:8333: Peer died      (4 connected, 4 pending, 9 max) 
Jan-31 22:12:21.802 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Waiting 1000 msec before next connect attempt to [c6ac4jdfyeiakex2.onion]:8333 
Jan-31 22:12:22.803 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [c6ac4jdfyeiakex2.onion]:8333     (4 connected, 5 pending, 9 max) 
Jan-31 22:12:23.217 [BlockingClient network thread for vlf5i3grro3wux24.onion:8333] INFO  o.b.core.Peer: Announcing to vlf5i3grro3wux24.onion:8333 as: /bitcoinj:0.14.4/Bisq:0.6.4/ 
Jan-31 22:12:24.000 [BlockingClient network thread for vlf5i3grro3wux24.onion:8333] INFO  o.b.core.Peer: [vlf5i3grro3wux24.onion]:8333: Got version=70015, subVer='/Satoshi:0.15.1/', services=0x13, time=2018-01-31 22:12:23, blocks=507037 
Jan-31 22:12:24.006 [BlockingClient network thread for vlf5i3grro3wux24.onion:8333] INFO  o.b.c.PeerGroup: [vlf5i3grro3wux24.onion]:8333: New peer      (5 connected, 4 pending, 9 max) 
Jan-31 22:12:24.136 [BlockingClient network thread for vlf5i3grro3wux24.onion:8333] INFO  o.b.core.Peer: Received alert from peer [vlf5i3grro3wux24.onion]:8333: URGENT: Alert key compromised, upgrade required 
Jan-31 22:12:27.064 [JavaFX Application Thread] INFO  i.b.n.p.p.g.RequestDataHandler: 
#################################################################
Connected to node: 3f3cu2yw7u457ztq.onion:8000
Received 158 instances
MailboxStoragePayload: 75
Alert: 1
Arbitrator: 2
OfferPayload: 80
################################################################# 
Jan-31 22:12:28.026 [Thread-13] INFO  i.b.n.p.n.TorNetworkNode: 
################################################################
Tor hidden service published after 35764 ms. Socked=HiddenServiceSocket[addr=2kkhbqawernv3qyb.onion,port=9999]
################################################################ 
Jan-31 22:12:28.116 [JavaFX Application Thread] INFO  i.b.n.p.p.g.RequestDataHandler: We send a GetUpdatedDataRequest to peer 5quyxpxheyvzmb2d.onion:8000.  
Jan-31 22:12:28.153 [JavaFX Application Thread] INFO  i.b.n.p.p.g.RequestDataHandler: We send a GetUpdatedDataRequest to peer 723ljisnynbtdohi.onion:8000.  
Jan-31 22:12:28.801 [BlockingClient network thread for fz6nsij6jiyuwlsc.onion:8333] INFO  o.b.core.Peer: Announcing to fz6nsij6jiyuwlsc.onion:8333 as: /bitcoinj:0.14.4/Bisq:0.6.4/ 
Jan-31 22:12:30.681 [BlockingClient network thread for fz6nsij6jiyuwlsc.onion:8333] INFO  o.b.core.Peer: [fz6nsij6jiyuwlsc.onion]:8333: Got version=70015, subVer='/Satoshi:0.15.1/', services=0x13, time=2018-01-31 22:12:08, blocks=507037 
Jan-31 22:12:30.745 [BlockingClient network thread for fz6nsij6jiyuwlsc.onion:8333] INFO  o.b.c.PeerGroup: [fz6nsij6jiyuwlsc.onion]:8333: New peer      (6 connected, 3 pending, 9 max) 
Jan-31 22:12:30.747 [BlockingClient network thread for fz6nsij6jiyuwlsc.onion:8333] INFO  o.b.core.Peer: Received alert from peer [fz6nsij6jiyuwlsc.onion]:8333: URGENT: Alert key compromised, upgrade required 
Jan-31 22:12:31.145 [BlockingClient network thread for c6ac4jdfyeiakex2.onion:8333] INFO  o.b.core.Peer: Announcing to c6ac4jdfyeiakex2.onion:8333 as: /bitcoinj:0.14.4/Bisq:0.6.4/ 
Jan-31 22:12:31.409 [JavaFX Application Thread] INFO  i.b.c.p.f.FeeService: BTC tx fee: txFeePerByte=60 
Jan-31 22:12:31.549 [JavaFX Application Thread] INFO  i.b.c.p.p.PriceFeedService: Received new marketPrice=MarketPrice(currencyCode=USD, price=10132.27, timestampSec=1517454680, isExternallyProvidedPrice=true) 7 sec. after request 
Jan-31 22:12:32.880 [BlockingClient network thread for c6ac4jdfyeiakex2.onion:8333] INFO  o.b.core.Peer: [c6ac4jdfyeiakex2.onion]:8333: Got version=70015, subVer='/Satoshi:0.15.1/', services=0x13, time=2018-01-31 22:12:31, blocks=507037 
Jan-31 22:12:33.226 [BlockingClient network thread for c6ac4jdfyeiakex2.onion:8333] INFO  o.b.c.PeerGroup: [c6ac4jdfyeiakex2.onion]:8333: New peer      (7 connected, 2 pending, 9 max) 
Jan-31 22:12:33.570 [BlockingClient network thread for c6ac4jdfyeiakex2.onion:8333] INFO  o.b.core.Peer: Received alert from peer [c6ac4jdfyeiakex2.onion]:8333: URGENT: Alert key compromised, upgrade required 
Jan-31 22:12:35.345 [JavaFX Application Thread] INFO  i.b.n.p.p.g.RequestDataHandler: 
#################################################################
Connected to node: 5quyxpxheyvzmb2d.onion:8000
Received 156 instances
MailboxStoragePayload: 75
Alert: 1
Arbitrator: 2
OfferPayload: 78
################################################################# 
Jan-31 22:12:36.479 [JavaFX Application Thread] INFO  i.b.n.p.p.PeerManager: Num of latestLivePeers=2, latestLivePeers=[Peer(nodeAddress=hs2eqa4l6pwnoy3u.onion:9999, date=Wed Jan 31 22:12:36 EST 2018, failedConnectionAttempts=0), Peer(nodeAddress=a7p7mrpslkixhi64.onion:9999, date=Wed Jan 31 22:12:36 EST 2018, failedConnectionAttempts=0)] 
Jan-31 22:12:38.194 [JavaFX Application Thread] INFO  i.b.n.p.p.PeerManager: Num of latestLivePeers=3, latestLivePeers=[Peer(nodeAddress=hs2eqa4l6pwnoy3u.onion:9999, date=Wed Jan 31 22:12:36 EST 2018, failedConnectionAttempts=0), Peer(nodeAddress=a7p7mrpslkixhi64.onion:9999, date=Wed Jan 31 22:12:36 EST 2018, failedConnectionAttempts=0), Peer(nodeAddress=fequ6jox537ixqot.onion:9999, date=Wed Jan 31 22:12:38 EST 2018, failedConnectionAttempts=0)] 
Jan-31 22:12:44.643 [JavaFX Application Thread] INFO  i.b.n.p.p.PeerManager: We have 6 connections open. Our limit is 12

**Comment by ManfredKarrer** [comment] 2018-02-01 15:15
That is fixed on 0.6.5. Please update again (sorry u prob just updated to 0.6.4. shortly before 0.6.5. went out)

**Closed as completed by ManfredKarrer** 2018-02-01 15:15 UTC
Labels: was:duplicate

**Comment by ciscoy2g17** [comment] 2018-02-02 02:11
Thank you kindly, Manfred. I noticed about two hours after posting this, that there was another update. I appreciate your feedback and hard work.

**Comment by cbeams** [comment] 2018-02-02 07:47
Duplicate of #1293
