### ISSUE TITLE
btcNodes option is treacherous

### ISSUE THREAD

**Issue by stiell** [bisq-network/bisq#794] opened 2017-04-05 03:42 UTC
The `--btcNodes` option has been mentioned ([1], [2]) as a way to avoid leaking one's wallet data by only using trusted Bitcoin nodes. However, I've found that unless used in a very specific way, this option will not behave as expected.

**Case 1**: I want to use a private Bitcoin node accessible via a `.onion` address. I start Bitsquare with `--btcNodes=example.onion`.
* **Expected behaviour**: Bitsquare connects only to example.onion, over Tor (default or previously configured). If this fails for any reason, it does not connect to any other node without user intervention.
* **Actual behaviour**: Bitsquare appears to ignore the specified address and connects to a list of random Bitcoin nodes.

**Case 2**: I want to use a private Bitcoin node accessible over a LAN/VPN. I start Bitsquare with `--btcNodes=192.0.2.1 --useTorForBtc false`.
* **Expected behaviour**: Bitsquare connects only to `192.0.2.1`. If this fails for any reason, it does not connect to any other node without user intervention.
* **Actual behaviour**: Bitsquare connects to `192.0.2.1`, but eventually also to several random Bitcoin nodes.

In one case Bitsquare also appeared to have silently disabled the option to use Tor, but I'm not able to reproduce this at the moment.

The only case where I've found it to work as expected is with `--btcNodes=127.0.0.1`.

[1]: https://github.com/bitsquare/bitsquare/issues/414#issuecomment-263673742
[2]: https://bitsquare.io/blog/privacy-in-bitsquare/

**Comment by ManfredKarrer** [comment] 2017-04-12 15:46
Sorry for the late reply...
Regarding Case 1: onion addresses are not supported yet in the options. 
@dan-da : I don't remember the exact reason why that had problems. Can we support that already?

Re Case 2: I will check, that sounds like a bug. If you pass your address it should no connect to any other nodes.

**Comment by ManfredKarrer** [comment] 2017-04-12 15:58
Re Case 2: I just tried with a normal IP (not LAN) and it worked like expected. Even after network connection loss it reconnected again like expected.
Can you try if you get the problem as well with not-LAN IPs?
If not then it seems to be related that the node is in LAN.
@dan-da Any idea?

**Comment by dan-da** [comment] 2017-04-13 06:50
Hmm, I just quickly reviewed both the AddrMessage path and regular Peer Discovery path.  At first blush, it seems that both paths do disable additional peers when btcNodes are specified.

One exception happens if nodes are specified by hostname and none can be resolved.  In that case, it falls back to regular peer discovery.  But that is not the case here, where the ip is specified directly.

To go further I would need to reproduce the issue and debug it.   I won't have time for that until next week, soonest.

**Comment by ripcurlx** [comment] 2020-01-28 11:13
Closing as this issue wasn't reproduced for a long time. @stiell Feel free to reopen if you still experience this problem with the current client.

**Closed as completed by ripcurlx** 2020-01-28 11:13 UTC
Labels: in:network, re:Bitcoin, re:Tor
