### ISSUE TITLE
Deprecate Revolut phone numbers, require Revolut username

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#4390] opened 2020-07-31 13:28 UTC
Due to the recent changes with Revolut, I feel we should make username usage mandatory. We should replace the payment account creation text validation to disallow phone numbers and only allow usernames.

cc @bisq-knight @leo816 @m52go

**Comment by ripcurlx** [comment] 2020-08-01 09:06
We have to do it similar as we did it with the move from e-mail to phone numbers in the past to be backwards compatible. But besides that :+1:

**Comment by wiz** [comment] 2020-08-01 13:05
Yeah, discussed with @m52go on a long call yesterday, we found your previous work, and fortunately the code is using a generic "accountId" string, so we are planning to change the string input validation.

**Comment by pingiun** [comment] 2020-08-07 15:13
This is a duplicate of #4155

**Closed as completed** 2020-08-07 15:41 UTC
Labels: in:payment-methods
