### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.sun.javafx.scene.control.skin.ProgressBarSkin

### ISSUE THREAD

**Issue by hosiawak** [bisq-network/bisq#566] opened 2016-08-04 16:03 UTC
```
karol@brenta:/Applications/Bitsquare.app/Contents/MacOS $ ./Bitsquare
sie-04 18:00:57.889 [JavaFX Application Thread] INFO  i.b.a.BitsquareApp: Log files under: /Users/karol/Library/Application Support/Bitsquare/bitsquare
sie-04 18:00:57.892 [JavaFX Application Thread] INFO  i.b.app.Version: Version{VERSION=0.4.9.2, P2P_NETWORK_VERSION=4, LOCAL_DB_VERSION=4, TRADE_PROTOCOL_VERSION=1, BTC_NETWORK_ID=0, getP2PNetworkId()=0}
sie-04 18:00:57.892 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.name: Mac OS X
sie-04 18:00:57.893 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.version: 10.11.5
sie-04 18:00:57.893 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.arch: x86_64
sie-04 18:00:57.893 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: sun.arch.data.model: 64
sie-04 18:00:57.893 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JRE: 1.8.0_92-b14 (Oracle Corporation)
sie-04 18:00:57.893 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JVM: 25.92-b14 (Java HotSpot(TM) 64-Bit Server VM)
sie-04 18:00:59.938 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread
sie-04 18:00:59.939 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableMessage= Could not initialize class com.sun.javafx.scene.control.skin.ProgressBarSkin
sie-04 18:00:59.939 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableClass= class java.lang.NoClassDefFoundError
sie-04 18:00:59.940 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Stack trace:
java.lang.NoClassDefFoundError: Could not initialize class com.sun.javafx.scene.control.skin.ProgressBarSkin
    at javafx.scene.control.ProgressBar.createDefaultSkin(ProgressBar.java:97)
    at javafx.scene.control.Control.impl_processCSS(Control.java:872)
    at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
    at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
    at javafx.scene.Node.processCSS(Node.java:9056)
    at javafx.scene.Node.processCSS(Node.java:9049)
    at javafx.scene.Scene.doCSSPass(Scene.java:545)
    at javafx.scene.Scene.access$3600(Scene.java:159)
    at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
    at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

java.lang.NoClassDefFoundError: Could not initialize class com.sun.javafx.scene.control.skin.ProgressBarSkin
    at javafx.scene.control.ProgressBar.createDefaultSkin(ProgressBar.java:97)
    at javafx.scene.control.Control.impl_processCSS(Control.java:872)
    at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
    at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
    at javafx.scene.Node.processCSS(Node.java:9056)
    at javafx.scene.Node.processCSS(Node.java:9049)
    at javafx.scene.Scene.doCSSPass(Scene.java:545)
    at javafx.scene.Scene.access$3600(Scene.java:159)
    at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
    at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
sie-04 18:01:00.346 [ STARTING] WARN  o.b.c.AbstractBlockChain: Wallet/chain height mismatch: 422868 vs 422875
```

**Comment by ManfredKarrer** [comment] 2016-08-04 18:42
Did you compile from source? If not just re install it. Never saw that before...

**Comment by hosiawak** [comment] 2016-08-04 20:45
I downloaded the latest .dmg I tried uninstalling but it happens again.

**Comment by ManfredKarrer** [comment] 2016-08-04 21:25
Seems you started it from the console? Just double click the app file. 
Seems it tries to use the System JDK when u start it that wasy (./Bitsquare) and u dont have all installed whats required (see docs/build.md in source code dir if u want to run form src code).

**Comment by hosiawak** [comment] 2016-08-05 08:26
It happens too when I double click the app file. I get:

<img width="575" alt="screen shot 2016-08-05 at 10 12 49" src="https://cloud.githubusercontent.com/assets/4709/17430609/788e3cf2-5af5-11e6-9950-853454b1b2df.png">

I'm not trying to run from a source code checkout. My system JDKs are 1.7.0_10-b18 (java7) and 1.8.0_25-b17 (java8). The log above shows 1.8.0_92-b14 which is the bundled JDK ?

**Comment by ManfredKarrer** [comment] 2016-08-06 21:36
Yes 1.8.0_92 is the bundled. if u run form source u need to follow the steps or the build script in the docs folder. No idea what causes that problem. On the mac I never saw any issues so far...

**Comment by ManfredKarrer** [comment] 2016-08-09 14:34
Could u resolve the issue? I think it is some system environment issue on your machine.

**Comment by hosiawak** [comment] 2016-08-10 07:18
I couldn't resolve the issue. I uninstalled it and removed `~/Library/Application Support/Bitsquare` dir. Then downloaded the latest release again `0.4.9.3` but the same issue persists.Feel free to close if I'm the only person who experiences it.

**Comment by ManfredKarrer** [comment] 2016-10-05 19:53
Do u still have the issue with the latest version? If so please re-open.

**Comment by hypno2000** [comment] 2016-12-10 17:28
Have exactly the same issue on macOS Sierra 10.12.1

**Comment by ManfredKarrer** [comment] 2016-12-10 19:48
Which Bitsquare version do u have? If not the newest, please update.

**Comment by hypno2000** [comment] 2016-12-11 00:03
fresh one, downloaded today

**Comment by hypno2000** [comment] 2016-12-11 00:06
```Dec-10 19:20:12.990 [JavaFX Application Thread] INFO  i.b.app.Version: Version{VERSION=0.4.9.8, P2P_NETWORK_VERSION=4, LOCAL_DB_VERSION=4, TRADE_PROTOCOL_VERSION=1, BTC_NETWORK_ID=0, getP2PNetworkId()=0}
Dec-10 19:20:12.990 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.name: Mac OS X
Dec-10 19:20:12.990 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.version: 10.12.1
Dec-10 19:20:12.990 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.arch: x86_64
Dec-10 19:20:12.990 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: sun.arch.data.model: 64
Dec-10 19:20:12.990 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JRE: 1.8.0_112-b16 (Oracle Corporation)
Dec-10 19:20:12.990 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JVM: 25.112-b16 (Java HotSpot(TM) 64-Bit Server VM)
Dec-10 19:20:13.668 [JavaFX Application Thread] INFO  i.b.b.p.PriceFeedService: baseUrl for PriceFeedService: http://t4wlzy7l6k4hnolg.onion/
Dec-10 19:20:18.383 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Error at displaying Throwable.
Dec-10 19:20:18.412 [JavaFX Application Thread] ERROR i.b.g.m.MainViewModel: initializeAllServices
Dec-10 19:20:18.474 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread
Dec-10 19:20:18.474 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableMessage= Could not initialize class com.sun.javafx.scene.control.skin.ProgressBarSkin
Dec-10 19:20:18.474 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableClass= class java.lang.NoClassDefFoundError
Dec-10 19:20:18.475 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Stack trace:
java.lang.NoClassDefFoundError: Could not initialize class com.sun.javafx.scene.control.skin.ProgressBarSkin
	at javafx.scene.control.ProgressBar.createDefaultSkin(ProgressBar.java:97)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)```

**Comment by hypno2000** [comment] 2016-12-11 00:07
effect is that the app window does not appear, but app keeps running

**Comment by pajasevi** [comment] 2017-03-07 15:10
Hey guys, I have the same issue. I updated Java and JDK, reinstalled Bitsquare, but the problem persists.

**Comment by ManfredKarrer** [comment] 2017-03-07 15:54
strange. i assume u dont run from source code but just start the Bisquare.app

**Comment by pajasevi** [comment] 2017-03-07 16:00
Hi Manfred. Yeah but strange thing is that when I start it via terminal, sometimes it runs and sometimes it throws this error. But when I start it by clicking on Bitsquare.app, it crashes everytime.

**Comment by ManfredKarrer** [comment] 2017-03-07 17:06
can u send me the log file?

**Comment by pajasevi** [comment] 2017-03-08 09:38
```
Bře-07 16:08:10.438 [JavaFX Application Thread] INFO  i.b.a.BitsquareApp: Log files under: /Users/pavelsevcik/Library/Application Support/Bitsquare/bitsquare
Bře-07 16:08:10.443 [JavaFX Application Thread] INFO  i.b.app.Version: Version{VERSION=0.4.9.9, P2P_NETWORK_VERSION=4, LOCAL_DB_VERSION=4, TRADE_PROTOCOL_VERSION=2, BTC_NETWORK_ID=0, getP2PNetworkId()=0}
Bře-07 16:08:10.444 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.name: Mac OS X
Bře-07 16:08:10.444 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.version: 10.10.3
Bře-07 16:08:10.444 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.arch: x86_64
Bře-07 16:08:10.444 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: sun.arch.data.model: 64
Bře-07 16:08:10.444 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JRE: 1.8.0_121-b13 (Oracle Corporation)
Bře-07 16:08:10.445 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JVM: 25.121-b13 (Java HotSpot(TM) 64-Bit Server VM)
Bře-07 16:08:11.467 [JavaFX Application Thread] INFO  i.b.b.p.PriceFeedService: baseUrl for PriceFeedService: http://t4wlzy7l6k4hnolg.onion/
Bře-07 16:08:15.260 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread
Bře-07 16:08:15.261 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableMessage= Could not initialize class com.sun.javafx.scene.control.skin.ProgressBarSkin
Bře-07 16:08:15.261 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableClass= class java.lang.NoClassDefFoundError
Bře-07 16:08:15.264 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Stack trace:
java.lang.NoClassDefFoundError: Could not initialize class com.sun.javafx.scene.control.skin.ProgressBarSkin
	at javafx.scene.control.ProgressBar.createDefaultSkin(ProgressBar.java:97)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

java.lang.NoClassDefFoundError: Could not initialize class com.sun.javafx.scene.control.skin.ProgressBarSkin
	at javafx.scene.control.ProgressBar.createDefaultSkin(ProgressBar.java:97)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Bře-07 16:08:21.318 [TorNetworkNode:CreateTorNode-9041] WARN  c.m.t.t.OnionProxyManager: Tor exited with value 1
Bře-07 16:08:21.321 [JavaFX Application Thread] ERROR i.b.p.n.TorNetworkNode: TorNode creation failed with exception: Could not Start Tor.
```

**Comment by ManfredKarrer** [comment] 2017-03-08 12:17
Very strange. This class is part of the jdk (fx). Could you try to re-install bitsquare? though dont expect that this will change really something, but have no idea what could cause that.

**Comment by pajasevi** [comment] 2017-03-08 13:11
You're right, strange. I reinstalled Bitsquare (for the fifth time) but this time it was after reinstallation of JDK. Now it works.

Thank you @ManfredKarrer, I'll buy you a coffee if you stop by Paralelní Polis ;-) (HCPP17 maybe?)

**Comment by ManfredKarrer** [comment] 2017-03-08 13:55
So you installed Bitsquare and then you installed jdk?
strange.... Bitsquare has a packed in jdk with some adjustments. so should be not interfere with OS jdk. do u have $JAVA_HOME setup manually or anything else?

HCPP17 would be great! :-)

**Comment by pajasevi** [comment] 2017-03-08 14:28
I tried Bitsquare like month ago and it worked, now this issue happened, so I reinstalled it like four times and nothing worked. Then I updated Java and JDK (I had some older Java 8) and it started working from the command line. Then I again reinstalled Bitsquare and now it works.

I have a suspicion that this is caused by closing the app using Cmd+Q (pretty standard way of closing apps in Mac OS) but it somehow cripples the app and it needs to be reinstalled.

**Comment by joachimneumann** [comment] 2018-09-03 21:29
I have this problem, too (MacOS 10.13.6). From my log file:

Sep-03 23:22:48.469 [main] INFO  b.c.u.Utilities: System info: os.name=Mac OS X; os.version=10.13.6; os.arch=x86_64; sun.arch.data.model=64; JRE=1.8.0_172-b11 (Oracle Corporation); JVM=25.172-b11 (Java HotSpot(TM) 64-Bit Server VM)
Sep-03 23:22:48.663 [main] INFO  b.c.app.Version: Version{VERSION=0.8.0, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=1, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10}
Sep-03 23:22:48.663 [main] INFO  b.c.s.CoreSetup: Path to Bisq jar file: /Applications/Bisq.app/Contents/Java/Bisq-0.8.0.jar
Sep-03 23:22:49.892 [JavaFX Application Thread] INFO  b.c.p.ProvidersRepository: Selected provider baseUrl=http://62nvujg5iou3vu3i.onion/, providerList=[http://62nvujg5iou3vu3i.onion/, http://5bmpx76qllutpcyp.onion/, http://44mgyoe2b6oqiytt.onion/, http://xc3nh4juf2hshy7e.onion/, http://ceaanhbvluug4we6.onion/]
Sep-03 23:22:51.070 [JavaFX Application Thread] ERROR b.d.app.BisqApp: Error during app init java.lang.ExceptionInInitializerError: null
	at javafx.scene.control.ProgressBar.createDefaultSkin(ProgressBar.java:97)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Node.processCSS(Node.java:9056)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.preferredSize(Scene.java:1643)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:864)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:940)
	at javafx.stage.Window.show(Window.java:955)
	at javafx.stage.Stage.show(Stage.java:259)
	at bisq.desktop.app.BisqApp.setupStage(BisqApp.java:235)
	at bisq.desktop.app.BisqApp.startApplication(BisqApp.java:123)
	at bisq.desktop.app.BisqAppMain.startApplication(BisqAppMain.java:121)
	at bisq.core.app.BisqExecutable.onApplicationLaunched(BisqExecutable.java:181)
	at bisq.desktop.app.BisqAppMain.onApplicationLaunched(BisqAppMain.java:89)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: java.lang.NullPointerException: null
	at com.sun.javafx.font.MacFontFinder.populateFontFileNameMap(MacFontFinder.java:99)
	at com.sun.javafx.font.PrismFontFactory.getFullNameToFileMap(PrismFontFactory.java:1740)
	at com.sun.javafx.font.PrismFontFactory.getFontResource(PrismFontFactory.java:469)
	at com.sun.javafx.font.LogicalFont.getSlot0Resource(LogicalFont.java:194)
	at com.sun.javafx.font.LogicalFont.getDefaultAAMode(LogicalFont.java:409)
	at com.sun.javafx.font.LogicalFont.getStrike(LogicalFont.java:413)
	at com.sun.javafx.font.PrismFont.getStrike(PrismFont.java:73)
	at com.sun.javafx.text.PrismTextLayout.setContent(PrismTextLayout.java:138)
	at javafx.scene.text.Text.getTextLayout(Text.java:229)
	at javafx.scene.text.Text.needsFullTextLayout(Text.java:184)
	at javafx.scene.text.Text.access$200(Text.java:95)
	at javafx.scene.text.Text$2.invalidated(Text.java:389)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:109)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.scene.text.Text.setText(Text.java:370)
	at javafx.scene.text.Text.<init>(Text.java:129)
	at com.sun.javafx.scene.control.skin.ProgressIndicatorSkin.<clinit>(ProgressIndicatorSkin.java:169)
	... 25 common frames omitted

**Comment by ManfredKarrer** [comment] 2018-09-03 21:40
@ripcurlx Do you have any idea? Maybe Java 10 solves that as well. Seems some font issue between jdk and osx...

Caused by: java.lang.NullPointerException: null
at com.sun.javafx.font.MacFontFinder.populateFontFileNameMap(MacFontFinder.java:99)

**Closed as completed** 2019-01-25 00:14 UTC
Labels: was:dropped
