### ISSUE TITLE
Localhost.9999 bug

### ISSUE THREAD

**Issue by leo816** [bisq-network/bisq#4123] opened 2020-04-06 11:45 UTC
### Description

User's onion address shows up as localhost.9999 and he is not able to receive any messages (on two cases it was the seller)
another mediator (@Bisq_Knight) had another case.

#### Version

1.2.9

### Steps to reproduce

Dealing with two mediation disputes I came across this.

### Expected behaviour

a normal onion address.

### Actual behaviour

It's simply not possible to get localhost as a network address.

### Screenshots

<img width="827" alt="bisq error" src="https://user-images.githubusercontent.com/54798241/78555195-cc416580-780c-11ea-9c56-91c1f86e6f89.png">
<img width="149" alt="Captura de pantalla 2020-04-05 a las 23 50 35" src="https://user-images.githubusercontent.com/54798241/78555268-f6932300-780c-11ea-9aa6-2ebd1096bf8b.png">

**Comment by ripcurlx** [comment] 2020-04-07 12:31
I think this is related to people using Bisq on Tails as far as I remember. @freimair Could you have a look at this? Thanks!

**Comment by freimair** [comment] 2020-04-08 08:47
duplicate of https://github.com/bisq-network/bisq/issues/3927

**Comment by freimair** [comment] 2020-04-08 09:01
I propose 2 steps:
- make it clear that `useLocalhostForP2P` cmdline option is for debugging and testing purposes only. In turn, if this option is set, set the base currency network away from `BTC_MAINNET`. That way, we cannot end up in the situation mentioned above.
- of course, that would disable Bisq for Tails users. Need to figure out what to do.

**Closed as completed** 2020-04-10 10:08 UTC
Labels: a:bug, on:Linux, is:critical

**Comment by freimair** [comment] 2020-04-10 13:30
https://bisq.wiki/Bisq_on_tails

thus, the issues #3927, #2278, #3791, #2841 can finally be closed properly (most of them already have been dropped already anyways)
