### ISSUE TITLE
Open disputes because of unconfirmed transactions

### ISSUE THREAD

**Issue by amuuza** [bisq-network/bisq#1031] opened 2017-11-29 11:19 UTC
My trade was completed even though the payout did not have 1 confirmation after many hours.
Sometimes Bisq may choose a too low fee to ever have a confirmation.
It would be nice to have a way to open a dispute in those cases.

**Comment by ManfredKarrer** [comment] 2017-11-29 12:37
Fee estimation is a difficult issue. If it is too high users complain if it is too low such cases can happen. Hard to find the right balance. It also depends on earlier unconfirmed txs in the chain (funding tx from external wallet is outside of our control). So far I have not got any other complaints that tx did not get confirmed in a reasonable time. But if so I will increase the fees again. You can open a dispute by cmd+o but you should not just because the deposit was delayed as long the trade period has not expired. Even if the period expires users con continue the trade. The option ot open a dispute is optional not mandatory.

**Comment by mrosseel** [comment] 2017-11-29 12:41
@ManfredKarrer I think the question is: SUPPOSE the multisig payout never confirms, what can the trader do? I tried in my Bisq and I couldn't open a dispute on a completed trade. Is this correct?

**Comment by ManfredKarrer** [comment] 2017-11-29 13:20
You can open a dispute also with a non confirmed dispute, though if the arbitrator close it will still be unconfirmed. A completed trade cannot be disputed as deposit is payout out. Beside in the April tx spam time where our tx fee were too low we never had issues with never confirming txs. If it happens the tx is just invalid so money has not left wallet but BitcoinJ does not handle that well. Was a bit of a mess back then but at the end all worked. SPV chain resync or restore from seeds was usually working to get a clean wallet again.

**Comment by amuuza** [comment] 2017-11-29 15:12
Well, if we are always able to open a dispute (through Ctrl+o or Alt+o in my case) then it's ok. I undestand there is no easy solution.
I guess this issue can be closed.

**Comment by ManfredKarrer** [comment] 2017-11-29 17:22
If there are more complaints regarding too long conf. time we will increase the fee estimation but then people complain about higher fees ;-(

**Comment by ripcurlx** [comment] 2018-12-19 16:06
Closing as complete. The counter starts now after the first block confirmation.

**Closed as completed by ripcurlx** 2018-12-19 16:06 UTC
