### ISSUE TITLE
Bisq connection impossible

### ISSUE THREAD

**Issue by 910314Jost** [bisq-network/bisq#7104] opened 2024-05-15 12:30 UTC
I can't connect to bisq for my first access.

I will describe the process step by step from when I open the application until the error at the end:

1st: Connecting to the Bitcoin network...

2nd: (2/4) Tor network node created...

3rd: (3/4) Published hidden service/Bitcoin network peers 0; 1; two; 3; 4.../ Bisq network peers 0; 1; two; 3; 4...

And at the end, a window appears asking me if I'm having connection problems and recommending deleting the outdated Tor files and restarting.

I use VPN. I tried changing my region, and also tried connecting Bisq with the VPN disabled, but to no avail.

Please someone help me?

**Comment by SparkyHS7** [comment] 2024-05-15 19:18
Yes im facing similar issue aswell

**Comment by swfsql** [comment] 2024-05-16 14:30
Also one can't confirm payment receipt if the connection is bad, even if the recipient already got the payment. Confirming is not allowed, with the message "Information: You need to wait until you have at least 4 connections to the Bitcoin network".
:(

**Comment by Giszmo** [comment] 2024-05-20 19:12
Might this be a duplicate of #3763? @SparkyHS7 and @910314Jost can you report your bisq version and check your bisq.log files, please?

**Comment by HenrikJannsen** [comment] 2024-05-27 16:27
Tor is suffering ddos attacks (https://metrics.torproject.org/torperf.html).
The next release will come with some improvements fro initial data loading which should improve a bit the issues.
If you can run locally a full Bitcoin node this greatly improves startup performance. 
See: https://bisq.community/t/psa-consider-running-your-own-bitcoin-node/12005

**Closed as not planned** 2024-09-02 00:19 UTC
Labels: was:dropped
