### ISSUE TITLE
Client unable to synch on DAO on startup

### ISSUE THREAD

**Issue by UnityJon** [bisq-network/bisq#2900] opened 2019-06-18 19:58 UTC
Last weds I went away for 6 days.  I had 6 open offers at the time and 1 open trade (which I opened a dispute on as the counter-party was late confirming).  Client was shut down whilst away.  On returning and starting up it consistently throws a java exception when trying to synch the DAO.  Looking at the log files it would seem linked to the (now closed) dispute.  I can view my offers but not edit or remove them.  I can also view wallets - but basically cant do any trades as the client can't synch the DAO.  At a guess it's because it was so long after the dispute was closed that the messages aren't available any more - but my client wants them.

I attach a log of my latest session - have tried plenty of times with same results (including rebuilding the DAO from genesis block).

[bisqlog.txt](https://github.com/bisq-network/bisq/files/3303195/bisqlog.txt)

**Comment by UnityJon** [comment] 2019-06-29 01:21
Sort of fixed this by deleting my disputelist file from the bisq data folder - stopped the client looking for whatever was causing the problem but, of course, lost records of my past disputes.  Treating the symptom not the cause of course.

**Comment by freimair** [comment] 2019-09-01 14:15
might be fixed by #3112. closed.

**Closed as completed by freimair** 2019-09-01 14:15 UTC

**Comment by chimp1984** [comment] 2019-09-01 14:40
No, the issue is not fixed yet. See: https://github.com/bisq-network/bisq/issues/3175
